const _ = require("lodash");
const forms = [
  {
    code: "D16019",
    displayName: "Nguyễn Lê Khôi Nguyên",
    department: "D6",
    managerName: "Dương Thị Nhung",
    managerCode: "D327",
    isManager: true,
    reviewerName1: "Nguyễn Kim Hưng",
    reviewerCode1: "D5093",
    reviewerName2: "Phan Lê Công Đạt",
    reviewerCode2: "D9005",
    reviewerName3: "Đặng Kim Xuân",
    reviewerCode3: "D4086",
    reviewerName4: "Đào Duy Bách",
    reviewerCode4: "D10144",
    reviewerName5: "Nguyễn Diễm Quỳnh",
    reviewerCode5: "D14705",
    reviewerName6: "Nhan Vương Ngọc Thạch",
    reviewerCode6: "D16480",
    reviewerName7: "Nguyễn Yến Linh",
    reviewerCode7: "D14478",
    reviewerName8: "Vũ Tuấn Dương",
    reviewerCode8: "D14755",
    reviewerName9: "Trương Thị Trà Giang",
    reviewerCode9: "D11150",
    reviewerName10: "Long Diệp Thành Nam ",
    reviewerCode10: "D7724",
    reviewerName11: "",
    reviewerCode11: "",
    reviewerName12: "",
    reviewerCode12: "",
    position: "Trợ lý vận hành kho Full-time",
  },
  {
    code: "D7381",
    displayName: "Huỳnh Bảo Nhi",
    department: "E12",
    managerName: "Dương Thị Nhung",
    managerCode: "D327",
    isManager: true,
    reviewerName1: "Nguyễn Kim Hưng",
    reviewerCode1: "D5093",
    reviewerName2: "Nguyễn Quang Bình",
    reviewerCode2: "D1906",
    reviewerName3: "Phan Lê Công Đạt",
    reviewerCode3: "D9005",
    reviewerName4: "Doãn Thị Ngọc Ánh",
    reviewerCode4: "D7287",
    reviewerName5: "Nguyễn Minh Hùng",
    reviewerCode5: "D4553",
    reviewerName6: "Mai Chiến Thắng",
    reviewerCode6: "D7363",
    reviewerName7: "Cát Trịnh Đức Bình",
    reviewerCode7: "D15222",
    reviewerName8: "Lê Thị Thanh Hà",
    reviewerCode8: "D15878",
    reviewerName9: "",
    reviewerCode9: "",
    reviewerName10: "",
    reviewerCode10: "",
    reviewerName11: "",
    reviewerCode11: "",
    reviewerName12: "",
    reviewerCode12: "",
    position: "Quản lý cơ sở Full-time",
  },
  {
    code: "D9005",
    displayName: "Phan Lê Công Đạt",
    department: "ECOM",
    managerName: "Dương Thị Nhung",
    managerCode: "D327",
    isManager: false,
    reviewerName1: "Nguyễn Kim Hưng",
    reviewerCode1: "D5093",
    reviewerName2: "Nguyễn Lê Khôi Nguyên",
    reviewerCode2: "D16019",
    reviewerName3: "Đặng Kim Xuân",
    reviewerCode3: "D4086",
    reviewerName4: "Nguyễn Minh Ngọc",
    reviewerCode4: "D479",
    reviewerName5: "Nguyễn Diễm Quỳnh",
    reviewerCode5: "D14705",
    reviewerName6: "",
    reviewerCode6: "",
    reviewerName7: "",
    reviewerCode7: "",
    reviewerName8: "",
    reviewerCode8: "",
    reviewerName9: "",
    reviewerCode9: "",
    reviewerName10: "",
    reviewerCode10: "",
    reviewerName11: "",
    reviewerCode11: "",
    reviewerName12: "",
    reviewerCode12: "",
    position: "Nhân viên Điều phối và Kinh doanh Full-time",
  },
  {
    code: "D4086",
    displayName: "Đặng Kim Xuân",
    department: "G4",
    managerName: "Dương Thị Nhung",
    managerCode: "D327",
    isManager: true,
    reviewerName1: "Đào Duy Bách",
    reviewerCode1: "D10144",
    reviewerName2: "Doãn Thị Ngọc Ánh",
    reviewerCode2: "D7287",
    reviewerName3: "Nguyễn Lê Khôi Nguyên",
    reviewerCode3: "D16019",
    reviewerName4: "Nguyễn Diễm Quỳnh",
    reviewerCode4: "D14705",
    reviewerName5: "Nguyễn Kim Hưng",
    reviewerCode5: "D5093",
    reviewerName6: "Nguyễn Đình Kháng",
    reviewerCode6: "D11054",
    reviewerName7: "Nguyễn Yến Linh",
    reviewerCode7: "D14478",
    reviewerName8: "Vũ Tuấn Dương",
    reviewerCode8: "D14755",
    reviewerName9: "Lý Trung Hậu",
    reviewerCode9: "D8013",
    reviewerName10: "Phan Lê Công Đạt",
    reviewerCode10: "D9005",
    reviewerName11: "",
    reviewerCode11: "",
    reviewerName12: "",
    reviewerCode12: "",
    position: "Quản lý Cơ sở Full-time",
  },
  {
    code: "D4553",
    displayName: "Nguyễn Minh Hùng",
    department: "IC",
    managerName: "Dương Thị Nhung",
    managerCode: "D327",
    isManager: true,
    reviewerName1: "Đào Duy Bách",
    reviewerCode1: "D10144",
    reviewerName2: "Bùi Thị Hương",
    reviewerCode2: "S78",
    reviewerName3: "Trương Thị Trà Giang",
    reviewerCode3: "D11150",
    reviewerName4: "Phạm Ngọc Hùng",
    reviewerCode4: "D15844",
    reviewerName5: "Chu Huy Thắng",
    reviewerCode5: "E09",
    reviewerName6: "Vũ Thúy Nhật",
    reviewerCode6: "D717",
    reviewerName7: "Bùi Thu Trang",
    reviewerCode7: "C635",
    reviewerName8: "Đặng Thị Thu Cúc",
    reviewerCode8: "D10256",
    reviewerName9: "Nguyễn Huyền Trang",
    reviewerCode9: "D703",
    reviewerName10: "Nguyễn Thị Thương",
    reviewerCode10: "D5762",
    reviewerName11: "",
    reviewerCode11: "",
    reviewerName12: "",
    reviewerCode12: "",
    position: "Nhân viên Kiểm toán nội bộ",
  },
  {
    code: "S78",
    displayName: "Bùi Thị Hương",
    department: "IC",
    managerName: "Dương Thị Nhung",
    managerCode: "D327",
    isManager: false,
    reviewerName1: "Dương Thị Nhung",
    reviewerCode1: "D327",
    reviewerName2: "Nguyễn Minh Hùng",
    reviewerCode2: "D4553",
    reviewerName3: "Bùi Thu Trang",
    reviewerCode3: "C635",
    reviewerName4: "Nguyễn Huyền Trang",
    reviewerCode4: "D703",
    reviewerName5: "Tạ Thu Hường",
    reviewerCode5: "D14111",
    reviewerName6: "",
    reviewerCode6: "",
    reviewerName7: "",
    reviewerCode7: "",
    reviewerName8: "",
    reviewerCode8: "",
    reviewerName9: "",
    reviewerCode9: "",
    reviewerName10: "",
    reviewerCode10: "",
    reviewerName11: "",
    reviewerCode11: "",
    reviewerName12: "",
    reviewerCode12: "",
    position: "Nhân viên kiểm toán nội bộ",
  },
  {
    code: "D10144",
    displayName: "Đào Duy Bách",
    department: "IC",
    managerName: "Dương Thị Nhung",
    managerCode: "D327",
    isManager: false,
    reviewerName1: "Nguyễn Minh Hùng",
    reviewerCode1: "D4553",
    reviewerName2: "Trương Thị Trà Giang",
    reviewerCode2: "D11150",
    reviewerName3: "Bùi Thu Trang",
    reviewerCode3: "C635",
    reviewerName4: "Nguyễn Hữu Long",
    reviewerCode4: "S41",
    reviewerName5: "Nguyễn Lê Khôi Nguyên",
    reviewerCode5: "D16019",
    reviewerName6: "",
    reviewerCode6: "",
    reviewerName7: "",
    reviewerCode7: "",
    reviewerName8: "",
    reviewerCode8: "",
    reviewerName9: "",
    reviewerCode9: "",
    reviewerName10: "",
    reviewerCode10: "",
    reviewerName11: "",
    reviewerCode11: "",
    reviewerName12: "",
    reviewerCode12: "",
    position: "Nhân viên Kiểm toán Full-time",
  },
  {
    code: "D5093",
    displayName: "Nguyễn Kim Hưng",
    department: "Kho",
    managerName: "Dương Thị Nhung",
    managerCode: "D327",
    isManager: true,
    reviewerName1: "Nguyễn Đình Kháng",
    reviewerCode1: "D11054",
    reviewerName2: "Nguyễn Thị Thương",
    reviewerCode2: "D5762",
    reviewerName3: "Bùi Thu Trang",
    reviewerCode3: "C635",
    reviewerName4: "Nguyễn Huyền Trang",
    reviewerCode4: "D703",
    reviewerName5: "Đặng Kim Xuân",
    reviewerCode5: "D4086",
    reviewerName6: "Nguyễn Lê Khôi Nguyên",
    reviewerCode6: "D16019",
    reviewerName7: "Huỳnh Bảo Nhi",
    reviewerCode7: "D7381",
    reviewerName8: "Nguyễn Thị Kim Hằng",
    reviewerCode8: "D8728",
    reviewerName9: "Lý Trung Hậu",
    reviewerCode9: "D8013",
    reviewerName10: "Đào Duy Bách",
    reviewerCode10: "D10144",
    reviewerName11: "",
    reviewerCode11: "",
    reviewerName12: "",
    reviewerCode12: "",
    position: "Nhân viên mua hàng Full-time",
  },
  {
    code: "D93",
    displayName: "Nguyễn Thúy Vi",
    department: "Training",
    managerName: "Dương Thị Nhung",
    managerCode: "D327",
    isManager: true,
    reviewerName1: "Giang Hương Ly",
    reviewerCode1: "D3267",
    reviewerName2: "Nguyễn Thành Nam",
    reviewerCode2: "D337",
    reviewerName3: "Doãn Thị Ngọc Ánh",
    reviewerCode3: "D7287",
    reviewerName4: "Cát Trịnh Đức Bình",
    reviewerCode4: "D15222",
    reviewerName5: "Vũ Tuấn Dương",
    reviewerCode5: "D14755",
    reviewerName6: "Nguyễn Thế Anh",
    reviewerCode6: "D583",
    reviewerName7: "Nguyễn Thị Thu Trang",
    reviewerCode7: "D1039",
    reviewerName8: "Nguyễn Yến Linh",
    reviewerCode8: "D14478",
    reviewerName9: "Trần Hương Trang",
    reviewerCode9: "D7178",
    reviewerName10: "Trần Việt Hoàng",
    reviewerCode10: "D14161",
    reviewerName11: "",
    reviewerCode11: "",
    reviewerName12: "",
    reviewerCode12: "",
    position: "Training Executive, TTL",
  },
  {
    code: "D14755",
    displayName: "Vũ Tuấn Dương",
    department: "Training",
    managerName: "Dương Thị Nhung",
    managerCode: "D327",
    isManager: false,
    reviewerName1: "Nguyễn Thúy Vi",
    reviewerCode1: "D93",
    reviewerName2: "Trương Thị Trà Giang",
    reviewerCode2: "D11150",
    reviewerName3: "Doãn Thị Ngọc Ánh",
    reviewerCode3: "D7287",
    reviewerName4: "Lê Mạnh Cường",
    reviewerCode4: "D16352",
    reviewerName5: "Nguyễn Thu Hiền",
    reviewerCode5: "D7527",
    reviewerName6: "Cát Trịnh Đức Bình",
    reviewerCode6: "D15222",
    reviewerName7: "",
    reviewerCode7: "",
    reviewerName8: "",
    reviewerCode8: "",
    reviewerName9: "",
    reviewerCode9: "",
    reviewerName10: "",
    reviewerCode10: "",
    reviewerName11: "",
    reviewerCode11: "",
    reviewerName12: "",
    reviewerCode12: "",
    position: "Nhân viên Đào tạo fulltime",
  },
  {
    code: "D15222",
    displayName: "Cát Trịnh Đức Bình",
    department: "Training",
    managerName: "Dương Thị Nhung",
    managerCode: "D327",
    isManager: false,
    reviewerName1: "Nguyễn Thúy Vi",
    reviewerCode1: "D93",
    reviewerName2: "Nguyễn Thị Thu Trang",
    reviewerCode2: "D1039",
    reviewerName3: "Dương Thị Trang",
    reviewerCode3: "D7395",
    reviewerName4: "Trần Thị Yến Vi",
    reviewerCode4: "D6249",
    reviewerName5: "Doãn Thị Ngọc Ánh",
    reviewerCode5: "D7287",
    reviewerName6: "Vũ Tuấn Dương",
    reviewerCode6: "D14755",
    reviewerName7: "",
    reviewerCode7: "",
    reviewerName8: "",
    reviewerCode8: "",
    reviewerName9: "",
    reviewerCode9: "",
    reviewerName10: "",
    reviewerCode10: "",
    reviewerName11: "",
    reviewerCode11: "",
    reviewerName12: "",
    reviewerCode12: "",
    position: "Nhân viên Đào tạo Full-time",
  },
  {
    code: "D5762",
    displayName: "Nguyễn Thị Thương",
    department: "VHKV",
    managerName: "Dương Thị Nhung",
    managerCode: "D327",
    isManager: true,
    reviewerName1: "",
    reviewerCode1: "",
    reviewerName2: "Lê Thị Hà Giang",
    reviewerCode2: "D16284",
    reviewerName3: "Lê Đỗ Phúc Vinh",
    reviewerCode3: "D8782",
    reviewerName4: "Nguyễn Thị Thu Trang",
    reviewerCode4: "D1039",
    reviewerName5: "Dương Thị Trang",
    reviewerCode5: "D7395",
    reviewerName6: "Nguyễn Hữu Long",
    reviewerCode6: "S41",
    reviewerName7: "Phạm Hoàng Yến",
    reviewerCode7: "D13808",
    reviewerName8: "Trương Thị Trà Giang",
    reviewerCode8: "D11150",
    reviewerName9: "Trần Thị Yến Vi",
    reviewerCode9: "D6249",
    reviewerName10: "Nguyễn Minh Hùng",
    reviewerCode10: "D4553",
    reviewerName11: "",
    reviewerCode11: "",
    reviewerName12: "",
    reviewerCode12: "",
    position: "Nhân viên giám sát chuỗi cửa hàng Full-time",
  },
  {
    code: "D16284",
    displayName: "Lê Thị Hà Giang",
    department: "VHKV",
    managerName: "Dương Thị Nhung",
    managerCode: "D327",
    isManager: false,
    reviewerName1: "Nguyễn Thị Thương",
    reviewerCode1: "D5762",
    reviewerName2: "Dương Thị Trang",
    reviewerCode2: "D7395",
    reviewerName3: "Vũ Trường Sơn",
    reviewerCode3: "D6100",
    reviewerName4: "Trần Hương Trang",
    reviewerCode4: "D7178",
    reviewerName5: "Lê Đỗ Phúc Vinh",
    reviewerCode5: "D8782",
    reviewerName6: "",
    reviewerCode6: "",
    reviewerName7: "",
    reviewerCode7: "",
    reviewerName8: "",
    reviewerCode8: "",
    reviewerName9: "",
    reviewerCode9: "",
    reviewerName10: "",
    reviewerCode10: "",
    reviewerName11: "",
    reviewerCode11: "",
    reviewerName12: "",
    reviewerCode12: "",
    position: "Nhân viên giám sát chuỗi cửa hàng Full-time",
  },
  {
    code: "D717",
    displayName: "Vũ Thúy Nhật",
    department: "BA",
    managerName: "Lê Tuấn Hiệp",
    managerCode: "F432",
    isManager: false,
    reviewerName1: "Nguyễn Đình Kháng",
    reviewerCode1: "D11054",
    reviewerName2: "Đinh Phương Thảo",
    reviewerCode2: "D708",
    reviewerName3: "Chu Huy Thắng",
    reviewerCode3: "E09",
    reviewerName4: "Nguyễn Huyền Trang",
    reviewerCode4: "D703",
    reviewerName5: "Nguyễn Minh Hùng",
    reviewerCode5: "D4553",
    reviewerName6: "",
    reviewerCode6: "",
    reviewerName7: "",
    reviewerCode7: "",
    reviewerName8: "",
    reviewerCode8: "",
    reviewerName9: "",
    reviewerCode9: "",
    reviewerName10: "",
    reviewerCode10: "",
    reviewerName11: "",
    reviewerCode11: "",
    reviewerName12: "",
    reviewerCode12: "",
    position: "Nhân viên BA",
  },
  {
    code: "D703",
    displayName: "Nguyễn Huyền Trang",
    department: "LEGAL",
    managerName: "Lê Tuấn Hiệp",
    managerCode: "F432",
    isManager: false,
    reviewerName1: "Nguyễn Minh Hùng",
    reviewerCode1: "D4553",
    reviewerName2: "Bùi Thị Hương",
    reviewerCode2: "S78",
    reviewerName3: " Nguyễn Cẩm Vân",
    reviewerCode3: "D16306",
    reviewerName4: "Vũ Thúy Nhật",
    reviewerCode4: "D717",
    reviewerName5: "Nguyễn Đình Kháng",
    reviewerCode5: "D11054",
    reviewerName6: "",
    reviewerCode6: "",
    reviewerName7: "",
    reviewerCode7: "",
    reviewerName8: "",
    reviewerCode8: "",
    reviewerName9: "",
    reviewerCode9: "",
    reviewerName10: "",
    reviewerCode10: "",
    reviewerName11: "",
    reviewerCode11: "",
    reviewerName12: "",
    reviewerCode12: "",
    position: "Legal Executive",
  },
  {
    code: "E09",
    displayName: "Chu Huy Thắng",
    department: "TECH",
    managerName: "Lê Tuấn Hiệp",
    managerCode: "F432",
    isManager: false,
    reviewerName1: "Đinh Phương Thảo",
    reviewerCode1: "D708",
    reviewerName2: "Vũ Thúy Nhật",
    reviewerCode2: "D717",
    reviewerName3: "Nguyễn Đình Kháng",
    reviewerCode3: "D11054",
    reviewerName4: "Trần Quốc Anh",
    reviewerCode4: "D7973",
    reviewerName5: "Lê Thị Chi",
    reviewerCode5: "D1931",
    reviewerName6: "",
    reviewerCode6: "",
    reviewerName7: "",
    reviewerCode7: "",
    reviewerName8: "",
    reviewerCode8: "",
    reviewerName9: "",
    reviewerCode9: "",
    reviewerName10: "",
    reviewerCode10: "",
    reviewerName11: "",
    reviewerCode11: "",
    reviewerName12: "",
    reviewerCode12: "",
    position: "Programming",
  },
  {
    code: "D708",
    displayName: "Đinh Phương Thảo",
    department: "TECH",
    managerName: "Lê Tuấn Hiệp",
    managerCode: "F432",
    isManager: false,
    reviewerName1: "Vũ Thúy Nhật",
    reviewerCode1: "D717",
    reviewerName2: "Chu Huy Thắng",
    reviewerCode2: "E09",
    reviewerName3: "Nguyễn Quang Bình",
    reviewerCode3: "D1906",
    reviewerName4: "Nguyễn Thế Anh",
    reviewerCode4: "D583",
    reviewerName5: "Trần Thủy Tiên",
    reviewerCode5: "D13006",
    reviewerName6: "",
    reviewerCode6: "",
    reviewerName7: "",
    reviewerCode7: "",
    reviewerName8: "",
    reviewerCode8: "",
    reviewerName9: "",
    reviewerCode9: "",
    reviewerName10: "",
    reviewerCode10: "",
    reviewerName11: "",
    reviewerCode11: "",
    reviewerName12: "",
    reviewerCode12: "",
    position: "Developer Full-time",
  },
  {
    code: "D1906",
    displayName: "Nguyễn Quang Bình",
    department: "CSKH",
    managerName: "Trần Anh Dũng",
    managerCode: "F688",
    isManager: true,
    reviewerName1: "Nguyễn Minh Ngọc",
    reviewerCode1: "D479",
    reviewerName2: "Trần Thủy Tiên",
    reviewerCode2: "D13006",
    reviewerName3: "Vũ Trường Sơn",
    reviewerCode3: "D6100",
    reviewerName4: "Nguyễn Thị Thu Trang",
    reviewerCode4: "D1039",
    reviewerName5: "Phạm Hoàng Yến",
    reviewerCode5: "D13808",
    reviewerName6: "Vũ Đặng Đức Anh",
    reviewerCode6: "D14601",
    reviewerName7: "Trương Hoàng Thu Trang",
    reviewerCode7: "D14409",
    reviewerName8: "Phạm Thanh Thảo",
    reviewerCode8: "D10463",
    reviewerName9: "",
    reviewerCode9: "",
    reviewerName10: "",
    reviewerCode10: "",
    reviewerName11: "",
    reviewerCode11: "",
    reviewerName12: "",
    reviewerCode12: "",
    position: "Nhân viên CSKH & Training Full-time",
  },
  {
    code: "D479",
    displayName: "Nguyễn Minh Ngọc",
    department: "ECOM",
    managerName: "Trần Anh Dũng",
    managerCode: "F688",
    isManager: true,
    reviewerName1: "Nguyễn Thị Hằng Nga",
    reviewerCode1: "D11108",
    reviewerName2: "Trần Thủy Tiên",
    reviewerCode2: "D13006",
    reviewerName3: "Nguyễn Quang Bình",
    reviewerCode3: "D1906",
    reviewerName4: "Đoàn Huy Hoàng",
    reviewerCode4: "D13918",
    reviewerName5: "Phan Lê Công Đạt",
    reviewerCode5: "D9005",
    reviewerName6: "Phạm Yến Nhi",
    reviewerCode6: "D12770",
    reviewerName7: "Nguyễn Đình Kháng",
    reviewerCode7: "D11054",
    reviewerName8: "Mai Thị Hiếu",
    reviewerCode8: "D9644",
    reviewerName9: "",
    reviewerCode9: "",
    reviewerName10: "",
    reviewerCode10: "",
    reviewerName11: "",
    reviewerCode11: "",
    reviewerName12: "",
    reviewerCode12: "",
    position: "Nhân viên vận hành sàn Thương mại điện tử",
  },
  {
    code: "D7954",
    displayName: "Dương Văn Vững",
    department: "HR1",
    managerName: "Trần Anh Dũng",
    managerCode: "F688",
    isManager: true,
    reviewerName1: "Doãn Thị Ngọc Ánh",
    reviewerCode1: "D7287",
    reviewerName2: "Nguyễn Minh Ngọc",
    reviewerCode2: "D479",
    reviewerName3: "Trần Thủy Tiên",
    reviewerCode3: "D13006",
    reviewerName4: "Lê Lộc Xuân Anh",
    reviewerCode4: "D14916",
    reviewerName5: "Đinh Bảo Trang",
    reviewerCode5: "D8991",
    reviewerName6: "Vũ Thị Thùy Linh",
    reviewerCode6: "D11244",
    reviewerName7: "",
    reviewerCode7: "",
    reviewerName8: "",
    reviewerCode8: "",
    reviewerName9: "",
    reviewerCode9: "",
    reviewerName10: "",
    reviewerCode10: "",
    reviewerName11: "",
    reviewerCode11: "",
    reviewerName12: "",
    reviewerCode12: "",
    position: "Quản lý Truyền thông tuyển dụng",
  },
  {
    code: "D7287",
    displayName: "Doãn Thị Ngọc Ánh",
    department: "HR2",
    managerName: "Trần Anh Dũng",
    managerCode: "F688",
    isManager: true,
    reviewerName1: "Dương Văn Vững",
    reviewerCode1: "D7954",
    reviewerName2: "Nguyễn Thúy Vi",
    reviewerCode2: "D93",
    reviewerName3: "Vũ Thị Thùy Linh",
    reviewerCode3: "D11244",
    reviewerName4: "Trần Thị Yến Vi",
    reviewerCode4: "D6249",
    reviewerName5: "Nguyễn Yến Linh",
    reviewerCode5: "D14478",
    reviewerName6: "Mai Chiến Thắng",
    reviewerCode6: "D7363",
    reviewerName7: "Phạm Thanh Trà",
    reviewerCode7: "D13986",
    reviewerName8: "Phùng Thị Lan Anh",
    reviewerCode8: "D15359",
    reviewerName9: "Nguyễn Duy Dân",
    reviewerCode9: "D15575",
    reviewerName10: "",
    reviewerCode10: "",
    reviewerName11: "",
    reviewerCode11: "",
    reviewerName12: "",
    reviewerCode12: "",
    position: "Quản lý Tuyển dụng",
  },
  {
    code: "D11244",
    displayName: "Vũ Thị Thùy Linh",
    department: "HR2",
    managerName: "Trần Anh Dũng",
    managerCode: "F688",
    isManager: false,
    reviewerName1: "Nguyễn Yến Linh",
    reviewerCode1: "D14478",
    reviewerName2: "Mai Chiến Thắng",
    reviewerCode2: "D7363",
    reviewerName3: "Nguyễn Duy Dân",
    reviewerCode3: "D15575",
    reviewerName4: "Doãn Thị Ngọc Ánh",
    reviewerCode4: "D7287",
    reviewerName5: "Nguyễn Đình Kháng",
    reviewerCode5: "D11054",
    reviewerName6: "",
    reviewerCode6: "",
    reviewerName7: "",
    reviewerCode7: "",
    reviewerName8: "",
    reviewerCode8: "",
    reviewerName9: "",
    reviewerCode9: "",
    reviewerName10: "",
    reviewerCode10: "",
    reviewerName11: "",
    reviewerCode11: "",
    reviewerName12: "",
    reviewerCode12: "",
    position: "Nhân viên Tuyển dụng Full-time",
  },
  {
    code: "D13006",
    displayName: "Trần Thủy Tiên",
    department: "MKT",
    managerName: "Trần Anh Dũng",
    managerCode: "F688",
    isManager: true,
    reviewerName1: "Nguyễn Thế Anh",
    reviewerCode1: "D583",
    reviewerName2: "Khuất Hải Yến",
    reviewerCode2: "D15862",
    reviewerName3: "Nguyễn Minh Ngọc",
    reviewerCode3: "D479",
    reviewerName4: "Nguyễn Quang Bình",
    reviewerCode4: "D1906",
    reviewerName5: "Đoàn Huy Hoàng",
    reviewerCode5: "D13918",
    reviewerName6: "Trần Thu Phương",
    reviewerCode6: "D15860",
    reviewerName7: "Nguyễn Thị Thúy Huyền",
    reviewerCode7: "D16397",
    reviewerName8: "Nguyễn Phương Nhi",
    reviewerCode8: "D14159",
    reviewerName9: "Trần Hà Ngân",
    reviewerCode9: "D16406",
    reviewerName10: "",
    reviewerCode10: "",
    reviewerName11: "",
    reviewerCode11: "",
    reviewerName12: "",
    reviewerCode12: "",
    position: "Nhân viên Marketing Full-time",
  },
  {
    code: "D6100",
    displayName: "Vũ Trường Sơn",
    department: "B4",
    managerName: "Trần Phương Anh",
    managerCode: "D388",
    isManager: true,
    reviewerName1: "Nguyễn Diễm Quỳnh",
    reviewerCode1: "D14705",
    reviewerName2: "Trần Quốc Anh",
    reviewerCode2: "D7973",
    reviewerName3: "Nguyễn Đình Kháng",
    reviewerCode3: "D11054",
    reviewerName4: "Phạm Thị Hồng Hạnh",
    reviewerCode4: "D14678",
    reviewerName5: "Nguyễn Yến Linh",
    reviewerCode5: "D14478",
    reviewerName6: "Bùi Quân Mạnh",
    reviewerCode6: "D14435",
    reviewerName7: "Nguyễn Thanh Thủy",
    reviewerCode7: "D9985",
    reviewerName8: "Trần Thị Khánh Huyền",
    reviewerCode8: "D16351",
    reviewerName9: "Vũ Ngô Hải Yến",
    reviewerCode9: "D15175",
    reviewerName10: "",
    reviewerCode10: "",
    reviewerName11: "",
    reviewerCode11: "",
    reviewerName12: "",
    reviewerCode12: "",
    position: "Quản lý bếp bánh Full-time",
  },
  {
    code: "D1039",
    displayName: "Nguyễn Thị Thu Trang",
    department: "B5",
    managerName: "Trần Phương Anh",
    managerCode: "D388",
    isManager: true,
    reviewerName1: "Nguyễn Yến Linh",
    reviewerCode1: "D14478",
    reviewerName2: "Nguyễn Diễm Quỳnh",
    reviewerCode2: "D14705",
    reviewerName3: "Trần Quốc Anh",
    reviewerCode3: "D7973",
    reviewerName4: "Nguyễn Đình Kháng",
    reviewerCode4: "D11054",
    reviewerName5: "Nguyễn Thành Nam",
    reviewerCode5: "D337",
    reviewerName6: "Nguyễn Thị Ngọc Trâm",
    reviewerCode6: "D9906",
    reviewerName7: "Nguyễn Hà Trang",
    reviewerCode7: "D13826",
    reviewerName8: "Nguyễn Thị Bích Hạnh",
    reviewerCode8: "D13288",
    reviewerName9: "Nguyễn Xuân Mai",
    reviewerCode9: "D11182",
    reviewerName10: "Nguyễn Ngọc Thuận",
    reviewerCode10: "D11252",
    reviewerName11: "",
    reviewerCode11: "",
    reviewerName12: "",
    reviewerCode12: "",
    position: "Quản lý Bếp bánh Full-time",
  },
  {
    code: "D13808",
    displayName: "Phạm Hoàng Yến",
    department: "B7",
    managerName: "Trần Phương Anh",
    managerCode: "D388",
    isManager: true,
    reviewerName1: "Nguyễn Yến Linh",
    reviewerCode1: "D14478",
    reviewerName2: "Nguyễn Diễm Quỳnh",
    reviewerCode2: "D14705",
    reviewerName3: "Nguyễn Minh Hùng",
    reviewerCode3: "D4553",
    reviewerName4: "Doãn Thị Ngọc Ánh",
    reviewerCode4: "D7287",
    reviewerName5: "Phạm Thị Lan",
    reviewerCode5: "D4857",
    reviewerName6: "Vũ Thị Quy",
    reviewerCode6: "D11281",
    reviewerName7: "Vũ Quỳnh Lan",
    reviewerCode7: "D12228",
    reviewerName8: "Đặng Thị Thu Cúc",
    reviewerCode8: "D10256",
    reviewerName9: "",
    reviewerCode9: "",
    reviewerName10: "",
    reviewerCode10: "",
    reviewerName11: "",
    reviewerCode11: "",
    reviewerName12: "",
    reviewerCode12: "",
    position: "Quản lý bếp bánh - Fulltime",
  },
  {
    code: "C635",
    displayName: "Bùi Thu Trang",
    department: "ĐG",
    managerName: "Trần Phương Anh",
    managerCode: "D388",
    isManager: true,
    reviewerName1: "Trương Thị Trà Giang",
    reviewerCode1: "D11150",
    reviewerName2: "Nguyễn Hữu Long",
    reviewerCode2: "S41",
    reviewerName3: "Mai Chiến Thắng",
    reviewerCode3: "D7363",
    reviewerName4: "Mai Thị Hiếu",
    reviewerCode4: "D9644",
    reviewerName5: "Nguyễn Đình Kháng",
    reviewerCode5: "D11054",
    reviewerName6: "Lê Thị Chi",
    reviewerCode6: "D1931",
    reviewerName7: "Đoàn Huy Hoàng",
    reviewerCode7: "D13918",
    reviewerName8: "Nguyễn Thu Hiền",
    reviewerCode8: "D7527",
    reviewerName9: "Nguyễn Hồng Phượng",
    reviewerCode9: "D16562",
    reviewerName10: "Lê Mạnh Cường",
    reviewerCode10: "D16352",
    reviewerName11: "",
    reviewerCode11: "",
    reviewerName12: "",
    reviewerCode12: "",
    position: "Quản lý đóng gói Full-time",
  },
  {
    code: "D6249",
    displayName: "Trần Thị Yến Vi",
    department: "E17-E20-M1",
    managerName: "Trần Phương Anh",
    managerCode: "D388",
    isManager: true,
    reviewerName1: "Đào Duy Bách",
    reviewerCode1: "D10144",
    reviewerName2: "Lê Thị Hà Giang",
    reviewerCode2: "D16284",
    reviewerName3: "Nguyễn Cẩm Vân",
    reviewerCode3: "D16306",
    reviewerName4: "Mai Chiến Thắng",
    reviewerCode4: "D7363",
    reviewerName5: "",
    reviewerCode5: "",
    reviewerName6: "Đỗ Hà An",
    reviewerCode6: "D11937",
    reviewerName7: "Phạm Thị Thu Hà",
    reviewerCode7: "D12462",
    reviewerName8: "Trần Thị Ngọc Linh",
    reviewerCode8: "D14744",
    reviewerName9: "Nguyễn Thanh Huyền",
    reviewerCode9: "D10184",
    reviewerName10: "",
    reviewerCode10: "",
    reviewerName11: "",
    reviewerCode11: "",
    reviewerName12: "",
    reviewerCode12: "",
    position: "Quản lý Cơ sở Full-time",
  },
  {
    code: "D4372",
    displayName: "Trần Thị Phương Mai",
    department: "E28-M2-E69",
    managerName: "Trần Phương Anh",
    managerCode: "D388",
    isManager: true,
    reviewerName1: "Đào Duy Bách",
    reviewerCode1: "D10144",
    reviewerName2: "Lê Thị Hà Giang",
    reviewerCode2: "D16284",
    reviewerName3: "Nguyễn Cẩm Vân",
    reviewerCode3: "D16306",
    reviewerName4: "Mai Chiến Thắng",
    reviewerCode4: "D7363",
    reviewerName5: "",
    reviewerCode5: "",
    reviewerName6: "Dương Hà My",
    reviewerCode6: "D8841",
    reviewerName7: "Lê Quang Bình",
    reviewerCode7: "D12305",
    reviewerName8: "Nguyễn Hồng Ánh",
    reviewerCode8: "D13557",
    reviewerName9: "",
    reviewerCode9: "",
    reviewerName10: "",
    reviewerCode10: "",
    reviewerName11: "",
    reviewerCode11: "",
    reviewerName12: "",
    reviewerCode12: "",
    position: "Quản lý cơ sở Full - time",
  },
  {
    code: "D7395",
    displayName: "Dương Thị Trang",
    department: "E8-E9-E27-E64",
    managerName: "Trần Phương Anh",
    managerCode: "D388",
    isManager: true,
    reviewerName1: "Đào Duy Bách",
    reviewerCode1: "D10144",
    reviewerName2: "Lê Thị Hà Giang",
    reviewerCode2: "D16284",
    reviewerName3: "Nguyễn Cẩm Vân",
    reviewerCode3: "D16306",
    reviewerName4: "Mai Chiến Thắng",
    reviewerCode4: "D7363",
    reviewerName5: "Nguyễn Thị Diệu Linh",
    reviewerCode5: "D15082",
    reviewerName6: "Đoàn Thị Mai Trang",
    reviewerCode6: "D15661",
    reviewerName7: "Nguyễn Thị Khánh Linh",
    reviewerCode7: "D16346",
    reviewerName8: "Phùng Thảo Linh",
    reviewerCode8: "D7780",
    reviewerName9: "Ngô An Thái Vy",
    reviewerCode9: "D12759",
    reviewerName10: "",
    reviewerCode10: "",
    reviewerName11: "",
    reviewerCode11: "",
    reviewerName12: "",
    reviewerCode12: "",
    position: "Quản lý Cơ sở Full-time",
  },
  {
    code: "D2537",
    displayName: "Nguyễn Văn Thao",
    department: "HC",
    managerName: "Trần Phương Anh",
    managerCode: "D388",
    isManager: false,
    reviewerName1: "Nguyễn Anh Tú",
    reviewerCode1: "E73",
    reviewerName2: "Phạm Văn Quế",
    reviewerCode2: "D11359",
    reviewerName3: "Nguyễn Thị Thu Trang",
    reviewerCode3: "D1039",
    reviewerName4: "Nguyễn Xuân Mai",
    reviewerCode4: "D11182",
    reviewerName5: "",
    reviewerCode5: "",
    reviewerName6: "",
    reviewerCode6: "",
    reviewerName7: "",
    reviewerCode7: "",
    reviewerName8: "",
    reviewerCode8: "",
    reviewerName9: "",
    reviewerCode9: "",
    reviewerName10: "",
    reviewerCode10: "",
    reviewerName11: "",
    reviewerCode11: "",
    reviewerName12: "",
    reviewerCode12: "",
    position: "Nhân viên Hậu cần Full-time",
  },
  {
    code: "D11359",
    displayName: "Phạm Văn Quế",
    department: "HC",
    managerName: "Trần Phương Anh",
    managerCode: "D388",
    isManager: false,
    reviewerName1: "Nguyễn Anh Tú",
    reviewerCode1: "E73",
    reviewerName2: "Nguyễn Văn Thao",
    reviewerCode2: "D2537",
    reviewerName3: "Trương Thị Trà Giang",
    reviewerCode3: "D11150",
    reviewerName4: "Bùi Thu Trang",
    reviewerCode4: "C635",
    reviewerName5: "Trần Thị Yến Vi",
    reviewerCode5: "D6249",
    reviewerName6: "",
    reviewerCode6: "",
    reviewerName7: "",
    reviewerCode7: "",
    reviewerName8: "",
    reviewerCode8: "",
    reviewerName9: "",
    reviewerCode9: "",
    reviewerName10: "",
    reviewerCode10: "",
    reviewerName11: "",
    reviewerCode11: "",
    reviewerName12: "",
    reviewerCode12: "",
    position: "Nhân viên Kỹ thuật điện nước Full-time",
  },
  {
    code: "E73",
    displayName: "Nguyễn Anh Tú",
    department: "HC",
    managerName: "Trần Phương Anh",
    managerCode: "D388",
    isManager: true,
    reviewerName1: "Nguyễn Văn Thao",
    reviewerCode1: "D2537",
    reviewerName2: "Phạm Văn Quế",
    reviewerCode2: "D11359",
    reviewerName3: "Trương Thị Trà Giang",
    reviewerCode3: "D11150",
    reviewerName4: "Dương Thị Trang",
    reviewerCode4: "D7395",
    reviewerName5: "Trần Thị Yến Vi",
    reviewerCode5: "D6249",
    reviewerName6: "Bùi Thu Trang",
    reviewerCode6: "C635",
    reviewerName7: "Vũ Trường Sơn",
    reviewerCode7: "D6100",
    reviewerName8: "Nguyễn Hữu Long",
    reviewerCode8: "S41",
    reviewerName9: "",
    reviewerCode9: "",
    reviewerName10: "",
    reviewerCode10: "",
    reviewerName11: "",
    reviewerCode11: "",
    reviewerName12: "",
    reviewerCode12: "",
    position: "Giám sát Hậu cần Full-time",
  },
  {
    code: "D11150",
    displayName: "Trương Thị Trà Giang",
    department: "KHO",
    managerName: "Trần Phương Anh",
    managerCode: "D388",
    isManager: true,
    reviewerName1: "Bùi Thu Trang",
    reviewerCode1: "C635",
    reviewerName2: "Mai Chiến Thắng",
    reviewerCode2: "D7363",
    reviewerName3: "Vũ Minh Hằng",
    reviewerCode3: "D14665",
    reviewerName4: "Mai Thị Hiếu",
    reviewerCode4: "D9644",
    reviewerName5: "Đào Duy Bách",
    reviewerCode5: "D10144",
    reviewerName6: "Đoàn Huy Hoàng",
    reviewerCode6: "D13918",
    reviewerName7: "Nguyễn Thu Hiền",
    reviewerCode7: "D7527",
    reviewerName8: "Nguyễn Hồng Phượng",
    reviewerCode8: "D16562",
    reviewerName9: "Tô Khánh Ly",
    reviewerCode9: "D16589",
    reviewerName10: "Phạm Thừa Vũ",
    reviewerCode10: "D16710",
    reviewerName11: "",
    reviewerCode11: "",
    reviewerName12: "",
    reviewerCode12: "",
    position: "Quản lý Kho Full - time",
  },
  {
    code: "S41",
    displayName: "Nguyễn Hữu Long",
    department: "KHO",
    managerName: "Trần Phương Anh",
    managerCode: "D388",
    isManager: true,
    reviewerName1: "Trương Thị Trà Giang",
    reviewerCode1: "D11150",
    reviewerName2: "Mai Chiến Thắng",
    reviewerCode2: "D7363",
    reviewerName3: "Vũ Minh Hằng",
    reviewerCode3: "D14665",
    reviewerName4: "Mai Thị Hiếu",
    reviewerCode4: "D9644",
    reviewerName5: "Đào Duy Bách",
    reviewerCode5: "D10144",
    reviewerName6: "Nguyễn Thu Hiền",
    reviewerCode6: "D7527",
    reviewerName7: "Nguyễn Hồng Phượng",
    reviewerCode7: "D16562",
    reviewerName8: "Tô Khánh Ly",
    reviewerCode8: "D16589",
    reviewerName9: "Nguyễn Thành Đạt",
    reviewerCode9: "D10894",
    reviewerName10: "Bùi Tuấn Quang",
    reviewerCode10: "D13574",
    reviewerName11: "",
    reviewerCode11: "",
    reviewerName12: "",
    reviewerCode12: "",
    position: "Quản lý Kho Full-time",
  },
  {
    code: "D14478",
    displayName: "Nguyễn Yến Linh",
    department: "Lịch trực",
    managerName: "Trần Phương Anh",
    managerCode: "D388",
    isManager: false,
    reviewerName1: "Nguyễn Thị Thu Trang",
    reviewerCode1: "D1039",
    reviewerName2: "Vũ Trường Sơn",
    reviewerCode2: "D6100",
    reviewerName3: "Phạm Thị Lan",
    reviewerCode3: "D4857",
    reviewerName4: "Nguyễn Thị Ngọc Trâm",
    reviewerCode4: "D9906",
    reviewerName5: "Đặng Kim Xuân",
    reviewerCode5: "D4086",
    reviewerName6: "Mai Chiến Thắng",
    reviewerCode6: "D7363",
    reviewerName7: "Doãn Thị Ngọc Ánh",
    reviewerCode7: "D7287",
    reviewerName8: "Nguyễn Thúy Vi",
    reviewerCode8: "D93",
    reviewerName9: "",
    reviewerCode9: "",
    reviewerName10: "",
    reviewerCode10: "",
    reviewerName11: "",
    reviewerCode11: "",
    reviewerName12: "",
    reviewerCode12: "",
    position: "Nhân viên Training Full-time",
  },
  {
    code: "D7363",
    displayName: "Mai Chiến Thắng",
    department: "Lịch trực",
    managerName: "Trần Phương Anh",
    managerCode: "D388",
    isManager: false,
    reviewerName1: "Trương Thị Trà Giang",
    reviewerCode1: "D11150",
    reviewerName2: "Nguyễn Hữu Long",
    reviewerCode2: "S41",
    reviewerName3: "Đặng Kim Xuân",
    reviewerCode3: "D4086",
    reviewerName4: "Dương Thị Trang",
    reviewerCode4: "D7395",
    reviewerName5: "Doãn Thị Ngọc Ánh",
    reviewerCode5: "D7287",
    reviewerName6: "Nguyễn Yến Linh",
    reviewerCode6: "D14478",
    reviewerName7: "Vũ Thị Thùy Linh",
    reviewerCode7: "D11244",
    reviewerName8: "Bùi Thu Trang",
    reviewerCode8: "D11150",
    reviewerName9: "",
    reviewerCode9: "",
    reviewerName10: "",
    reviewerCode10: "",
    reviewerName11: "",
    reviewerCode11: "",
    reviewerName12: "",
    reviewerCode12: "",
    position: "Nhân viên tổ chức vận hành Full-time",
  },
  {
    code: "D9644",
    displayName: "Mai Thị Hiếu",
    department: "Log",
    managerName: "Trần Phương Anh",
    managerCode: "D388",
    isManager: true,
    reviewerName1: "Bùi Thu Trang",
    reviewerCode1: "C635",
    reviewerName2: "Lê Thị Chi",
    reviewerCode2: "D1931",
    reviewerName3: "Nguyễn Đình Kháng",
    reviewerCode3: "D11054",
    reviewerName4: "Vũ Minh Hằng",
    reviewerCode4: "D14665",
    reviewerName5: "Dương Thị Trang",
    reviewerCode5: "D7395",
    reviewerName6: "Nguyễn Thị Quỳnh Nga",
    reviewerCode6: "D15394",
    reviewerName7: "Phan Lê Công Đạt",
    reviewerCode7: "D9005",
    reviewerName8: "",
    reviewerCode8: "",
    reviewerName9: "",
    reviewerCode9: "",
    reviewerName10: "",
    reviewerCode10: "",
    reviewerName11: "",
    reviewerCode11: "",
    reviewerName12: "",
    reviewerCode12: "",
    position: "Nhân viên Logistic Full-time",
  },
  {
    code: "D1931",
    displayName: "Lê Thị Chi",
    department: "Log",
    managerName: "Trần Phương Anh",
    managerCode: "D388",
    isManager: false,
    reviewerName1: "Nguyễn Đình Kháng",
    reviewerCode1: "D11054",
    reviewerName2: "Trương Thị Trà Giang",
    reviewerCode2: "D11150",
    reviewerName3: "Bùi Thu Trang",
    reviewerCode3: "C635",
    reviewerName4: "Dương Thị Trang",
    reviewerCode4: "D7395",
    reviewerName5: "Mai Thị Hiếu",
    reviewerCode5: "D9644",
    reviewerName6: "",
    reviewerCode6: "",
    reviewerName7: "",
    reviewerCode7: "",
    reviewerName8: "",
    reviewerCode8: "",
    reviewerName9: "",
    reviewerCode9: "",
    reviewerName10: "",
    reviewerCode10: "",
    reviewerName11: "",
    reviewerCode11: "",
    reviewerName12: "",
    reviewerCode12: "",
    position: "Giám sát chất lượng vận hành Full-time",
  },
  {
    code: "D9985",
    displayName: "Nguyễn Thanh Thủy",
    department: "Thợ bánh ",
    managerName: "Trần Phương Anh",
    managerCode: "D388",
    isManager: false,
    reviewerName1: "Bùi Quân Mạnh",
    reviewerCode1: "D14435",
    reviewerName2: "Hoàng Thị Duyên",
    reviewerCode2: "D14716",
    reviewerName3: "Vũ Trường Sơn",
    reviewerCode3: "D6100",
    reviewerName4: "Trần Thị Khánh Huyền",
    reviewerCode4: "D16351",
    reviewerName5: "",
    reviewerCode5: "",
    reviewerName6: "",
    reviewerCode6: "",
    reviewerName7: "",
    reviewerCode7: "",
    reviewerName8: "",
    reviewerCode8: "",
    reviewerName9: "",
    reviewerCode9: "",
    reviewerName10: "",
    reviewerCode10: "",
    reviewerName11: "",
    reviewerCode11: "",
    reviewerName12: "",
    reviewerCode12: "",
    position: "Thợ bánh Full-time",
  },
  {
    code: "D13288",
    displayName: "Nguyễn Thị Bích Hạnh",
    department: "Thợ bánh ",
    managerName: "Trần Phương Anh",
    managerCode: "D388",
    isManager: false,
    reviewerName1: "Nguyễn Thị Ngọc Trâm",
    reviewerCode1: "D9906",
    reviewerName2: "Nguyễn Thị Thu Trang",
    reviewerCode2: "D1039",
    reviewerName3: "Nguyễn Xuân Mai",
    reviewerCode3: "D11182",
    reviewerName4: "Bùi Phương Liên",
    reviewerCode4: "D14658",
    reviewerName5: "",
    reviewerCode5: "",
    reviewerName6: "",
    reviewerCode6: "",
    reviewerName7: "",
    reviewerCode7: "",
    reviewerName8: "",
    reviewerCode8: "",
    reviewerName9: "",
    reviewerCode9: "",
    reviewerName10: "",
    reviewerCode10: "",
    reviewerName11: "",
    reviewerCode11: "",
    reviewerName12: "",
    reviewerCode12: "",
    position: "Thợ bánh Full-time",
  },
  {
    code: "D14658",
    displayName: "Bùi Phương Liên",
    department: "Thợ bánh ",
    managerName: "Trần Phương Anh",
    managerCode: "D388",
    isManager: false,
    reviewerName1: "Nguyễn Thị Ngọc Trâm",
    reviewerCode1: "D9906",
    reviewerName2: "Nguyễn Thị Thu Trang",
    reviewerCode2: "D1039",
    reviewerName3: "Nguyễn Xuân Mai",
    reviewerCode3: "D11182",
    reviewerName4: "Nguyễn Hà Trang",
    reviewerCode4: "D13826",
    reviewerName5: "",
    reviewerCode5: "",
    reviewerName6: "",
    reviewerCode6: "",
    reviewerName7: "",
    reviewerCode7: "",
    reviewerName8: "",
    reviewerCode8: "",
    reviewerName9: "",
    reviewerCode9: "",
    reviewerName10: "",
    reviewerCode10: "",
    reviewerName11: "",
    reviewerCode11: "",
    reviewerName12: "",
    reviewerCode12: "",
    position: "Thợ bánh Full-time",
  },
  {
    code: "D9906",
    displayName: "Nguyễn Thị Ngọc Trâm",
    department: "Thợ bánh ",
    managerName: "Trần Phương Anh",
    managerCode: "D388",
    isManager: false,
    reviewerName1: "Nguyễn Thị Thu Trang",
    reviewerCode1: "D1039",
    reviewerName2: "Nguyễn Thị Bích Hạnh",
    reviewerCode2: "D13288",
    reviewerName3: "Nguyễn Xuân Mai",
    reviewerCode3: "D11182",
    reviewerName4: "Nguyễn Thúy Vi",
    reviewerCode4: "D93",
    reviewerName5: "Nguyễn Yến Linh",
    reviewerCode5: "D14478",
    reviewerName6: "",
    reviewerCode6: "",
    reviewerName7: "",
    reviewerCode7: "",
    reviewerName8: "",
    reviewerCode8: "",
    reviewerName9: "",
    reviewerCode9: "",
    reviewerName10: "",
    reviewerCode10: "",
    reviewerName11: "",
    reviewerCode11: "",
    reviewerName12: "",
    reviewerCode12: "",
    position: "Thợ bánh Full-time",
  },
  {
    code: "D4857",
    displayName: "Phạm Thị Lan",
    department: "Thợ bánh ",
    managerName: "Trần Phương Anh",
    managerCode: "D388",
    isManager: false,
    reviewerName1: "Phạm Hoàng Yến",
    reviewerCode1: "D13808",
    reviewerName2: "Vũ Quỳnh Lan",
    reviewerCode2: "D12228",
    reviewerName3: "Nguyễn Yến Linh",
    reviewerCode3: "D14478",
    reviewerName4: "Nguyễn Diễm Quỳnh",
    reviewerCode4: "D14705",
    reviewerName5: "",
    reviewerCode5: "",
    reviewerName6: "",
    reviewerCode6: "",
    reviewerName7: "",
    reviewerCode7: "",
    reviewerName8: "",
    reviewerCode8: "",
    reviewerName9: "",
    reviewerCode9: "",
    reviewerName10: "",
    reviewerCode10: "",
    reviewerName11: "",
    reviewerCode11: "",
    reviewerName12: "",
    reviewerCode12: "",
    position: "Thợ bánh Full-time",
  },
  {
    code: "D11281",
    displayName: "Vũ Thị Quy",
    department: "Thợ bánh ",
    managerName: "Trần Phương Anh",
    managerCode: "D388",
    isManager: false,
    reviewerName1: "Phạm Thị Lan",
    reviewerCode1: "D4857",
    reviewerName2: "Phạm Hoàng Yến",
    reviewerCode2: "D13808",
    reviewerName3: "Vũ Quỳnh Lan",
    reviewerCode3: "D12228",
    reviewerName4: "",
    reviewerCode4: "",
    reviewerName5: "",
    reviewerCode5: "",
    reviewerName6: "",
    reviewerCode6: "",
    reviewerName7: "",
    reviewerCode7: "",
    reviewerName8: "",
    reviewerCode8: "",
    reviewerName9: "",
    reviewerCode9: "",
    reviewerName10: "",
    reviewerCode10: "",
    reviewerName11: "",
    reviewerCode11: "",
    reviewerName12: "",
    reviewerCode12: "",
    position: "Thợ bánh Full-time",
  },
  {
    code: "D7721",
    displayName: "Trịnh Văn Tiến",
    department: "TX",
    managerName: "Trần Phương Anh",
    managerCode: "D388",
    isManager: false,
    reviewerName1: "Nguyễn Anh Tú",
    reviewerCode1: "E73",
    reviewerName2: "Nguyễn Thị Thu Trang",
    reviewerCode2: "D1039",
    reviewerName3: "Phạm Văn Quế",
    reviewerCode3: "D11359",
    reviewerName4: "Trần Thị Phương Mai",
    reviewerCode4: "D4372",
    reviewerName5: "",
    reviewerCode5: "",
    reviewerName6: "",
    reviewerCode6: "",
    reviewerName7: "",
    reviewerCode7: "",
    reviewerName8: "",
    reviewerCode8: "",
    reviewerName9: "",
    reviewerCode9: "",
    reviewerName10: "",
    reviewerCode10: "",
    reviewerName11: "",
    reviewerCode11: "",
    reviewerName12: "",
    reviewerCode12: "",
    position: "Tài xế giao hàng xe bán tải",
  },
  {
    code: "D8132",
    displayName: "Hoàng Anh Tuấn",
    department: "TX",
    managerName: "Trần Phương Anh",
    managerCode: "D388",
    isManager: false,
    reviewerName1: "Nguyễn Anh Tú",
    reviewerCode1: "E73",
    reviewerName2: "Nguyễn Hữu Long",
    reviewerCode2: "S41",
    reviewerName3: "Phạm Văn Quế",
    reviewerCode3: "D11359",
    reviewerName4: "Dương Thị Trang",
    reviewerCode4: "D7395",
    reviewerName5: "Phạm Hoàng Yến",
    reviewerCode5: "D13808",
    reviewerName6: "",
    reviewerCode6: "",
    reviewerName7: "",
    reviewerCode7: "",
    reviewerName8: "",
    reviewerCode8: "",
    reviewerName9: "",
    reviewerCode9: "",
    reviewerName10: "",
    reviewerCode10: "",
    reviewerName11: "",
    reviewerCode11: "",
    reviewerName12: "",
    reviewerCode12: "",
    position: "Tài xế giao hàng xe tải đông lạnh",
  },
  {
    code: "D8013",
    displayName: "Lý Trung Hậu",
    department: "CB",
    managerName: "Vy Tuấn Anh",
    managerCode: "F262",
    isManager: false,
    reviewerName1: "Bùi Thu Trang",
    reviewerCode1: "C635",
    reviewerName2: "Nguyễn Hồng Phượng",
    reviewerCode2: "D16562",
    reviewerName3: "Nguyễn Huyền Trang",
    reviewerCode3: "D703",
    reviewerName4: "Giang Hương Ly",
    reviewerCode4: "D3267",
    reviewerName5: "Nguyễn Yến Linh",
    reviewerCode5: "D14478",
    reviewerName6: "",
    reviewerCode6: "",
    reviewerName7: "",
    reviewerCode7: "",
    reviewerName8: "",
    reviewerCode8: "",
    reviewerName9: "",
    reviewerCode9: "",
    reviewerName10: "",
    reviewerCode10: "",
    reviewerName11: "",
    reviewerCode11: "",
    reviewerName12: "",
    reviewerCode12: "",
    position: "Nhân viên Chính sách nhân sự Full-time",
  },
  {
    code: "S110",
    displayName: "Nguyễn Văn Việt",
    department: "MEDIA",
    managerName: "Vy Tuấn Anh",
    managerCode: "F262",
    isManager: false,
    reviewerName1: "Đinh Phương Thảo",
    reviewerCode1: "D708",
    reviewerName2: "Nguyễn Thành Nam",
    reviewerCode2: "D337",
    reviewerName3: "Nguyễn Thế Anh",
    reviewerCode3: "D583",
    reviewerName4: "Trần Thủy Tiên",
    reviewerCode4: "D13006",
    reviewerName5: "Nguyễn Anh Tú",
    reviewerCode5: "E73",
    reviewerName6: "",
    reviewerCode6: "",
    reviewerName7: "",
    reviewerCode7: "",
    reviewerName8: "",
    reviewerCode8: "",
    reviewerName9: "",
    reviewerCode9: "",
    reviewerName10: "",
    reviewerCode10: "",
    reviewerName11: "",
    reviewerCode11: "",
    reviewerName12: "",
    reviewerCode12: "",
    position: "Graphic Designer, TTL",
  },
  {
    code: "D3267",
    displayName: "Giang Hương Ly",
    department: "MKT",
    managerName: "Vy Tuấn Anh",
    managerCode: "F262",
    isManager: false,
    reviewerName1: "Nguyễn Thế Anh",
    reviewerCode1: "D583",
    reviewerName2: "Khuất Hải Yến",
    reviewerCode2: "D15862",
    reviewerName3: "Trần Thủy Tiên",
    reviewerCode3: "D13006",
    reviewerName4: "Dương Văn Vững",
    reviewerCode4: "D7954",
    reviewerName5: "Ngụy Thị Ngọc Anh",
    reviewerCode5: "D16358",
    reviewerName6: "",
    reviewerCode6: "",
    reviewerName7: "",
    reviewerCode7: "",
    reviewerName8: "",
    reviewerCode8: "",
    reviewerName9: "",
    reviewerCode9: "",
    reviewerName10: "",
    reviewerCode10: "",
    reviewerName11: "",
    reviewerCode11: "",
    reviewerName12: "",
    reviewerCode12: "",
    position: "Nhân viên Marketing Full-time",
  },
  {
    code: "D7973",
    displayName: "Trần Quốc Anh",
    department: "Purchasing",
    managerName: "Vy Tuấn Anh",
    managerCode: "F262",
    isManager: false,
    reviewerName1: "Nguyễn Đình Kháng",
    reviewerCode1: "D11054",
    reviewerName2: "Vũ Minh Hằng",
    reviewerCode2: "D14665",
    reviewerName3: "Nguyễn Diễm Quỳnh",
    reviewerCode3: "D14705",
    reviewerName4: "Mai Thị Hiếu",
    reviewerCode4: "D9644",
    reviewerName5: "Nguyễn Thị Thu Trang",
    reviewerCode5: "D1039",
    reviewerName6: "",
    reviewerCode6: "",
    reviewerName7: "",
    reviewerCode7: "",
    reviewerName8: "",
    reviewerCode8: "",
    reviewerName9: "",
    reviewerCode9: "",
    reviewerName10: "",
    reviewerCode10: "",
    reviewerName11: "",
    reviewerCode11: "",
    reviewerName12: "",
    reviewerCode12: "",
    position: "Nhân viên Mua hàng Full-time",
  },
  {
    code: "D14665",
    displayName: "Vũ Minh Hằng",
    department: "Purchasing",
    managerName: "Vy Tuấn Anh",
    managerCode: "F262",
    isManager: false,
    reviewerName1: "Nguyễn Đình Kháng",
    reviewerCode1: "D11054",
    reviewerName2: "Trần Quốc Anh",
    reviewerCode2: "D7973",
    reviewerName3: "Nguyễn Diễm Quỳnh",
    reviewerCode3: "D14705",
    reviewerName4: "Mai Thị Hiếu",
    reviewerCode4: "D9644",
    reviewerName5: "Trương Thị Trà Giang",
    reviewerCode5: "D11150",
    reviewerName6: "",
    reviewerCode6: "",
    reviewerName7: "",
    reviewerCode7: "",
    reviewerName8: "",
    reviewerCode8: "",
    reviewerName9: "",
    reviewerCode9: "",
    reviewerName10: "",
    reviewerCode10: "",
    reviewerName11: "",
    reviewerCode11: "",
    reviewerName12: "",
    reviewerCode12: "",
    position: "Nhân viên mua hàng Full-time",
  },
  {
    code: "D14705",
    displayName: "Nguyễn Diễm Quỳnh",
    department: "Purchasing",
    managerName: "Vy Tuấn Anh",
    managerCode: "F262",
    isManager: false,
    reviewerName1: "Nguyễn Đình Kháng",
    reviewerCode1: "D11054",
    reviewerName2: "Trần Quốc Anh",
    reviewerCode2: "D7973",
    reviewerName3: "Nguyễn Hữu Long",
    reviewerCode3: "S41",
    reviewerName4: "Mai Thị Hiếu",
    reviewerCode4: "D9644",
    reviewerName5: "Nguyễn Thị Thu Trang",
    reviewerCode5: "D1039",
    reviewerName6: "",
    reviewerCode6: "",
    reviewerName7: "",
    reviewerCode7: "",
    reviewerName8: "",
    reviewerCode8: "",
    reviewerName9: "",
    reviewerCode9: "",
    reviewerName10: "",
    reviewerCode10: "",
    reviewerName11: "",
    reviewerCode11: "",
    reviewerName12: "",
    reviewerCode12: "",
    position: "Nhân viên mua hàng Full-time",
  },
  {
    code: "D11054",
    displayName: "Nguyễn Đình Kháng",
    department: "Purchasing",
    managerName: "Vy Tuấn Anh",
    managerCode: "F262",
    isManager: true,
    reviewerName1: "Nguyễn Lê Khôi Nguyên",
    reviewerCode1: "D16019",
    reviewerName2: "Trần Quốc Anh",
    reviewerCode2: "D7973",
    reviewerName3: "Vũ Minh Hằng",
    reviewerCode3: "D14665",
    reviewerName4: "Nguyễn Diễm Quỳnh",
    reviewerCode4: "D14705",
    reviewerName5: "Phạm Thị Hồng Hạnh",
    reviewerCode5: "D14678",
    reviewerName6: "Mai Thị Hiếu",
    reviewerCode6: "D9644",
    reviewerName7: "Lê Thị Chi",
    reviewerCode7: "D1931",
    reviewerName8: "Vũ Thúy Nhật",
    reviewerCode8: "D717",
    reviewerName9: "Phan Lê Công Đạt",
    reviewerCode9: "D9005",
    reviewerName10: "Đặng Kim Xuân",
    reviewerCode10: "D4086",
    reviewerName11: "Tô Khánh Ly",
    reviewerCode11: "D16589",
    reviewerName12: "Long Diệp Thành Nam",
    reviewerCode12: "D7724",
    position: "Nhân viên mua hàng Full-time",
  },
  {
    code: "D583",
    displayName: "Nguyễn Thế Anh",
    department: "R&D",
    managerName: "Vy Tuấn Anh",
    managerCode: "F262",
    isManager: false,
    reviewerName1: "Nguyễn Thành Nam",
    reviewerCode1: "D337",
    reviewerName2: "Nguyễn Văn Việt",
    reviewerCode2: "S110",
    reviewerName3: "Giang Hương Ly",
    reviewerCode3: "D3267",
    reviewerName4: "Trần Thủy Tiên",
    reviewerCode4: "D13006",
    reviewerName5: "Nguyễn Thúy Vi",
    reviewerCode5: "D93",
    reviewerName6: "",
    reviewerCode6: "",
    reviewerName7: "",
    reviewerCode7: "",
    reviewerName8: "",
    reviewerCode8: "",
    reviewerName9: "",
    reviewerCode9: "",
    reviewerName10: "",
    reviewerCode10: "",
    reviewerName11: "",
    reviewerCode11: "",
    reviewerName12: "",
    reviewerCode12: "",
    position: "Nhân viên R&D Full-time",
  },
  {
    code: "D337",
    displayName: "Nguyễn Thành Nam",
    department: "R&D",
    managerName: "Vy Tuấn Anh",
    managerCode: "F262",
    isManager: false,
    reviewerName1: "Nguyễn Thế Anh",
    reviewerCode1: "D583",
    reviewerName2: "Nguyễn Đình Kháng",
    reviewerCode2: "D11054",
    reviewerName3: "Nguyễn Văn Việt",
    reviewerCode3: "S110",
    reviewerName4: "Nguyễn Minh Ngọc",
    reviewerCode4: "D479",
    reviewerName5: "Khuất Hải Yến",
    reviewerCode5: "D15862",
    reviewerName6: "",
    reviewerCode6: "",
    reviewerName7: "",
    reviewerCode7: "",
    reviewerName8: "",
    reviewerCode8: "",
    reviewerName9: "",
    reviewerCode9: "",
    reviewerName10: "",
    reviewerCode10: "",
    reviewerName11: "",
    reviewerCode11: "",
    reviewerName12: "",
    reviewerCode12: "",
    position: "Kitchen Manager, Training Executive, TTL",
  },
  {
    code: "D15862",
    displayName: "Khuất Hải Yến",
    department: "TIKTOK",
    managerName: "Vy Tuấn Anh",
    managerCode: "F262",
    isManager: false,
    reviewerName1: "Nguyễn Thành Nam",
    reviewerCode1: "D337",
    reviewerName2: "Giang Hương Ly",
    reviewerCode2: "D3267",
    reviewerName3: "Trần Thủy Tiên",
    reviewerCode3: "D13006",
    reviewerName4: "Dương Văn Vững",
    reviewerCode4: "D7954",
    reviewerName5: "Ngụy Thị Ngọc Anh",
    reviewerCode5: "D16358",
    reviewerName6: "",
    reviewerCode6: "",
    reviewerName7: "",
    reviewerCode7: "",
    reviewerName8: "",
    reviewerCode8: "",
    reviewerName9: "",
    reviewerCode9: "",
    reviewerName10: "",
    reviewerCode10: "",
    reviewerName11: "",
    reviewerCode11: "",
    reviewerName12: "",
    reviewerCode12: "",
    position: "Trợ lý xây dựng kênh Tiktok",
  },
];

const managers = _.map(
  _.reduce(
    forms,
    (result, form) => {
      if (form.managerCode) {
        result[form.managerCode] = result[form.managerCode] || {
          code: form.managerCode,
          displayName: form.managerName,
          reviewees: [],
        };
        result[form.managerCode].reviewees.push(form);
      }
      return result;
    },
    {}
  )
);
const isManager = (code) => {
  return _.find(managers, { code: code });
};
const getRevieweesForManager = (code) => {
  return _.find(managers, { code: code }).reviewees;
};
module.exports = { isManager, getRevieweesForManager };
