const _ = require("lodash");

const forms = [
  {
    code: "D3982",
    displayName: "Hoàng Văn Luýt",
    department: "HCM",
    position: "Quản lý vận hành kho",
    email: "hvl.luyt@gmail.com",
    managerName: "Dương Thị Nhung",
    managerCode: "D327",
  },
  {
    code: "D4553",
    displayName: "Nguyễn Minh Hùng",
    department: "Kiểm toán",
    position: "Kiểm toán viên nội bộ",
    email: "Ngminhhung1102@gmail.com",
    managerName: "Dương Thị Nhung",
    managerCode: "D327",
  },
  {
    code: "D5915",
    displayName: "Phùng Hải Long",
    department: "Kiểm toán",
    position: "Kiểm toán viên nội bộ",
    email: "longphung.2105@gmail.com",
    managerName: "Dương Thị Nhung",
    managerCode: "D327",
  },
  {
    code: "D570",
    displayName: "Hà Thị Trà My ",
    department: "QC",
    position: "Nhân viên giám sát chất lượng",
    email: "hathitramy2512@gmail.com\t",
    managerName: "Dương Thị Nhung",
    managerCode: "D327",
  },
  {
    code: "D6794",
    displayName: "Hoàng Đình Hiếu",
    department: "QC",
    position: "Nhân viên giám sát chất lượng",
    email: "hieuuuu2002@gmail.com",
    managerName: "Dương Thị Nhung",
    managerCode: "D327",
  },
  {
    code: "D6795",
    displayName: "Trần Thị Hiền",
    department: "QC",
    position: "Nhân viên giám sát chất lượng",
    email: "tranhien1996.hn@gmail.com",
    managerName: "Dương Thị Nhung",
    managerCode: "D327",
  },
  {
    code: "D7886",
    displayName: "Đàm Dĩnh Thanh",
    department: "QC",
    position: "Nhân viên giám sát chất lượng",
    email: "damdinhthanh.97@gmail.com",
    managerName: "Dương Thị Nhung",
    managerCode: "D327",
  },
  {
    code: "S78",
    displayName: "Bùi Thị Hương",
    department: "Kho - ĐG",
    position: "Kiểm toán viên nội bộ",
    email: "buihuong17101997@gmail.com",
    managerName: "Dương Thị Nhung",
    managerCode: "D327",
  },
  {
    code: "D8492",
    displayName: "Vương Cẩm Tú",
    department: "Logistics",
    position: "Nhân viên điều phối Full - time",
    email: "camtu3224@gmail.com",
    managerName: "Dương Thị Nhung",
    managerCode: "D327",
  },
  {
    code: "D708",
    displayName: "Đinh Phương Thảo",
    department: "Tech",
    position: "Lập trình viên Full stack",
    email: "dinhphuongthaoqia@gmail.com",
    managerName: "Lê Tuấn Hiệp",
    managerCode: "F432",
  },
  {
    code: "D4309",
    displayName: "Nguyễn Văn Cương",
    department: "BS",
    position: "Chuyên viên phân tích dữ liệu",
    email: "cuongnv.1512@gmail.com",
    managerName: "Lê Tuấn Hiệp",
    managerCode: "F432",
  },
  {
    code: "D5939",
    displayName: "Nguyễn Đắc Dũng",
    department: "KT",
    position: "Kế toán tổng hợp",
    email: "dungdark97@gmail.com",
    managerName: "Lê Tuấn Hiệp",
    managerCode: "F432",
  },
  {
    code: "D703",
    displayName: "Nguyễn Huyền Trang",
    department: "Pháp chế",
    position: "Chuyên viên pháp chế",
    email: "Blackpage60@gmail.com",
    managerName: "Lê Tuấn Hiệp",
    managerCode: "F432",
  },
  {
    code: "E09",
    displayName: "Chu Huy Thắng",
    department: "Tech",
    position: "Lập trình viên Full stack",
    email: "chuthang205@gmail.com",
    managerName: "Lê Tuấn Hiệp",
    managerCode: "F432",
  },
  {
    code: "D1969",
    displayName: "Trần Hương Mai",
    department: "Cơ sở",
    position: "Quản lý cơ sở fulltime",
    email: "huongmai04112000@gmail.com",
    managerName: "Trần Anh Dũng",
    managerCode: "F688",
  },
  {
    code: "D248",
    displayName: "Ngô Dương Hương",
    department: "Cơ sở",
    position: "Quản lý cơ sở fulltime",
    email: "ngoduonghuong@gmail.com",
    managerName: "Trần Anh Dũng",
    managerCode: "F688",
  },
  {
    code: "D7395",
    displayName: "Dương Thị Trang",
    department: "Cơ sở",
    position: "Quản lý cơ sở fulltime",
    email: "trangduong11899@gmail.com",
    managerName: "Trần Anh Dũng",
    managerCode: "F688",
  },
  {
    code: "D931",
    displayName: "Ngô Thị Huyền",
    department: "Cơ sở",
    position: "Quản lý cơ sở fulltime",
    email: "huyennt66@wru.vn",
    managerName: "Trần Anh Dũng",
    managerCode: "F688",
  },
  {
    code: "S146",
    displayName: "Bùi Văn Vương",
    department: "HC",
    position: "Nhân viên kỹ thuật nội thất",
    email: "vuong7815@gmail.com",
    managerName: "Trần Anh Dũng",
    managerCode: "F688",
  },
  {
    code: "D2537",
    displayName: "Nguyễn Văn Thao",
    department: "HC",
    position: "Nhân viên kỹ thuật điện nước",
    email: "ngocthao060690@gmail.com",
    managerName: "Trần Anh Dũng",
    managerCode: "F688",
  },
  {
    code: "D3793",
    displayName: "Trương Văn Vỹ",
    department: "HC",
    position: "IT helpdesk",
    email: "truongvybhtv@gmail.com",
    managerName: "Trần Anh Dũng",
    managerCode: "F688",
  },
  {
    code: "E73",
    displayName: "Nguyễn Anh Tú",
    department: "HC",
    position: "IT helpdesk",
    email: "anhtuas123@gmail.com",
    managerName: "Trần Anh Dũng",
    managerCode: "F688",
  },
  {
    code: "D7287",
    displayName: "Doãn Thị Ngọc Ánh",
    department: "HR2",
    position: "Chuyên viên Tuyển dụng",
    email: "doanthingocanh1605@gmail.com",
    managerName: "Trần Anh Dũng",
    managerCode: "F688",
  },
  {
    code: "D7954",
    displayName: "Dương Văn Vững",
    department: "HR2",
    position: "Chuyên viên Tuyển dụng",
    email: "duongvung1003@gmail.com",
    managerName: "Trần Anh Dũng",
    managerCode: "F688",
  },
  {
    code: "D79",
    displayName: "Nguyễn Thị Mỹ Linh",
    department: "Training",
    position: "Chuyên viên đào tạo và phát triển",
    email: "linhxu271196@gmail.com",
    managerName: "Trần Anh Dũng",
    managerCode: "F688",
  },
  {
    code: "D93",
    displayName: "Nguyễn Thúy Vi",
    department: "Training",
    position: "Chuyên viên đào tạo và phát triển",
    email: "thuyvi11196@gmail.com",
    managerName: "Trần Anh Dũng",
    managerCode: "F688",
  },
  {
    code: "D479",
    displayName: "Nguyễn Minh Ngọc",
    department: "Training",
    position: "Chuyên viên đào tạo và phát triển",
    email: "hastagminhngoc@gmail.com",
    managerName: "Trần Anh Dũng",
    managerCode: "F688",
  },
  {
    code: "D717",
    displayName: "Vũ Thúy Nhật",
    department: "Training",
    position: "Chuyên viên đào tạo và phát triển",
    email: "v.thuy.nhatt@gmail.com",
    managerName: "Trần Anh Dũng",
    managerCode: "F688",
  },
  {
    code: "D1394",
    displayName: "Nguyễn Trường Giang",
    department: "B1",
    position: "Quản lý sản xuất bếp",
    email: "giangmda1810@gmail.com",
    managerName: "Trần Phương Anh",
    managerCode: "D388",
  },
  {
    code: "S41",
    displayName: "Nguyễn Hữu Long",
    department: "Kho - ĐG",
    position: "Quản lý vận hành kho",
    email: "nhlong2107@gmail.com",
    managerName: "Trần Phương Anh",
    managerCode: "D388",
  },
  {
    code: "D557",
    displayName: "Vũ Thị Lành",
    department: "Kho - ĐG",
    position: "Quản lý sản xuất bếp",
    email: "vulanhk59bka@gmail.com",
    managerName: "Trần Phương Anh",
    managerCode: "D388",
  },
  {
    code: "C635",
    displayName: "Bùi Thu Trang",
    department: "Kho - ĐG",
    position: "Quản lý đóng gói",
    email: "trytowin1003@gmail.com",
    managerName: "Trần Phương Anh",
    managerCode: "D388",
  },
  {
    code: "D5093",
    displayName: "Nguyễn Kim Hưng",
    department: "Kho - ĐG",
    position: "Chuyên viên mua hàng",
    email: "ngungsuong.nkh97@gmail.com",
    managerName: "Vy Tuấn Anh",
    managerCode: "F262",
  },
  {
    code: "M30",
    displayName: "Lê Thị Mơ",
    department: "Marketing",
    position: "Marketing",
    email: "lemoql1996@gmail.com",
    managerName: "Vy Tuấn Anh",
    managerCode: "F262",
  },
  {
    code: "D388",
    displayName: "Trần Phương Anh",
    department: "Kho - ĐG",
    position: "Trưởng phòng kho vận",
    email: "tpa2498@gmail.com",
    managerName: "Vy Tuấn Anh",
    managerCode: "F262",
  },
  {
    code: "S110",
    displayName: "Nguyễn Văn Việt",
    department: "OFFICE",
    position: "Graphic Designer",
    email: "vietxc2014@gmail.com",
    managerName: "Vy Tuấn Anh",
    managerCode: "F262",
  },
  {
    code: "D5169",
    displayName: "Vũ Thị Linh Chi",
    department: "Purchasing",
    position: "Chuyên viên mua hàng",
    email: "chinaxu137@gmail.com",
    managerName: "Vy Tuấn Anh",
    managerCode: "F262",
  },
  {
    code: "D5841",
    displayName: "Lò Thị Khánh Lâm",
    department: "Purchasing",
    position: "Chuyên viên mua hàng",
    email: "khanhlam3108@gmail.com",
    managerName: "Vy Tuấn Anh",
    managerCode: "F262",
  },
  {
    code: "D327",
    displayName: "Dương Thị Nhung",
    department: "QC",
    position: "Quality Supervisor Manager",
    email: "duongnhung65@gmail.com",
    managerName: "Vy Tuấn Anh",
    managerCode: "F262",
  },
  {
    code: "D337",
    displayName: "Nguyễn Thành Nam",
    department: "R&D",
    position: "Nhân viên phát triển sản phẩm",
    email: "thanhnam06121997@gmail.com",
    managerName: "Vy Tuấn Anh",
    managerCode: "F262",
  },
];

const managers = _.map(
  _.reduce(
    forms,
    (result, form) => {
      if (form.managerCode) {
        result[form.managerCode] = result[form.managerCode] || {
          code: form.managerCode,
          displayName: form.managerName,
          reviewees: [],
        };
        result[form.managerCode].reviewees.push(form);
      }
      return result;
    },
    {}
  )
);

const isManager = (code) => {
  return _.find(managers, { code: code });
};

const getRevieweesForManager = (code) => {
  return _.find(managers, { code: code }).reviewees;
};

module.exports = {
  isManager,
  getRevieweesForManager,
};
