import { makeAutoObservable } from "mobx";
import { RootStore } from "./RootStore";

export class CriterionStore {
  rootStore: RootStore;

  criterionPositions = criteriaPositions;

  constructor(rootStore: RootStore) {
    this.rootStore = rootStore;

    makeAutoObservable(this, {
      rootStore: false,
    });
  }

  getMatchingCriterions(position: string) {
    return this.criterionPositions.filter((criterionPosition) => {
      return criterionPosition.positions.includes(position);
    });
  }
}

const criteriaPositions = [
  {
    group: "Attitude",
    criterion: "Trung thực, thẳng thắn",
    positions: [
      "Quản lý cơ sở",
      "Quản lý cơ sở fulltime",
      "Kế toán tổng hợp",
      "Kế toán thuế",
      "Nhân viên bếp fulltime",
      "Nhân viên giám sát chất lượng",
      "Kiểm toán viên nội bộ",
    ],
  },
  {
    group: "Attitude",
    criterion: "Tỉ mỉ, cẩn thận",
    positions: [
      "Chuyên viên mua hàng",
      "Nhân viên phát triển sản phẩm",
      "Graphic Designer",
      "Quản lý vận hành kho",
      "Quản lý vận hành đóng gói",
      "Nhân viên điều phối Full - time",
      "Trưởng phòng kho vận",
      "Kế toán tổng hợp",
      "Kế toán thuế",
      "Chuyên viên phân tích dữ liệu",
      "Chuyên viên pháp chế",
      "Quản lý sản xuất bếp",
      "Nhân viên bếp fulltime",
      "Nhân viên giám sát chất lượng",
      "Kiểm toán viên nội bộ",
      "Chuyên viên Tuyển dụng",
      "Chuyên viên nhân sự tổng hợp",
      "Chuyên viên đào tạo và phát triển",
    ],
  },
  {
    group: "Attitude",
    criterion: "Nhạy bén",
    positions: [
      "Chuyên viên mua hàng",
      "Nhân viên phát triển sản phẩm",
      "Graphic Designer",
      "Nhân viên điều phối Full - time",
      "IT helpdesk",
      "Nhân viên kỹ thuật nội thất",
      "Nhân viên kỹ thuật điện nước",
      "Kế toán tổng hợp",
      "Kế toán thuế",
      "Chuyên viên phân tích dữ liệu",
      "Chuyên viên pháp chế",
      "Nhân viên giám sát chất lượng",
      "Kiểm toán viên nội bộ",
      "Chăm sóc khách hàng",
      "Chuyên viên Tuyển dụng",
      "Chuyên viên nhân sự tổng hợp",
      "Chuyên viên đào tạo và phát triển",
    ],
  },
  {
    group: "Attitude",
    criterion: "Kiên trì",
    positions: [
      "Chuyên viên mua hàng",
      "Nhân viên phát triển sản phẩm",
      "Graphic Designer",
      "Quản lý cơ sở",
      "Quản lý cơ sở fulltime",
      "Saleadmin",
      "Quản lý sản xuất bếp",
      "Nhân viên bếp fulltime",
      "Kiểm toán viên nội bộ",
      "Chuyên viên Tuyển dụng",
      "Chuyên viên nhân sự tổng hợp",
      "Chuyên viên đào tạo và phát triển",
    ],
  },
  {
    group: "Attitude",
    criterion: "Kỷ luật",
    positions: [
      "Quản lý vận hành kho",
      "Quản lý vận hành đóng gói",
      "Trưởng phòng kho vận",
      "Visual Merchandiser",
      "Chuyên viên pháp chế",
      "Quản lý sản xuất bếp",
      "Nhân viên bếp fulltime",
      "Nhân viên giám sát chất lượng",
      "Kiểm toán viên nội bộ",
      "Chăm sóc khách hàng",
    ],
  },
  {
    group: "Attitude",
    criterion: "Phản hồi nhanh",
    positions: [
      "Quản lý vận hành kho",
      "Quản lý vận hành đóng gói",
      "Nhân viên điều phối Full - time",
      "Quản lý cơ sở",
      "Quản lý cơ sở fulltime",
      "Trưởng phòng kho vận",
      "IT helpdesk",
      "Nhân viên kỹ thuật nội thất",
      "Nhân viên kỹ thuật điện nước",
      "Saleadmin",
      "Lập trình viên Full stack",
      "Business Analyst",
      "Kế toán tổng hợp",
      "Kế toán thuế",
      "Chuyên viên phân tích dữ liệu",
      "Quản lý sản xuất bếp",
      "Nhân viên giám sát chất lượng",
      "Kiểm toán viên nội bộ",
      "Chăm sóc khách hàng",
    ],
  },
  {
    group: "Attitude",
    criterion: "Tinh thần chịu trách nhiệm",
    positions: [
      "Quản lý vận hành kho",
      "Quản lý vận hành đóng gói",
      "Nhân viên điều phối Full - time",
      "Quản lý cơ sở",
      "Quản lý cơ sở fulltime",
      "Trưởng phòng kho vận",
      "IT helpdesk",
      "Nhân viên kỹ thuật nội thất",
      "Nhân viên kỹ thuật điện nước",
      "Visual Merchandiser",
      "Nhân viên bếp fulltime",
    ],
  },
  {
    group: "Attitude",
    criterion: "Tinh thần lạc quan",
    positions: ["Saleadmin", "Visual Merchandiser"],
  },
  {
    group: "Attitude",
    criterion: "Nhiệt tình",
    positions: ["Lập trình viên Full stack", "Nhân viên bếp fulltime"],
  },
  {
    group: "Attitude",
    criterion: "Cam kết",
    positions: [
      "Lập trình viên Full stack",
      "Business Analyst",
      "Kế toán tổng hợp",
      "Chuyên viên phân tích dữ liệu",
    ],
  },
  {
    group: "Attitude",
    criterion: "Đổi mới, sáng tạo",
    positions: [
      "Visual Merchandiser",
      "Lập trình viên Full stack",
      "Business Analyst",
      "Quản lý sản xuất bếp",
      "Kiểm toán viên nội bộ",
    ],
  },
  {
    group: "Skill",
    criterion: "Kỹ năng thuyết trình",
    positions: ["Visual Merchandiser", "Business Analyst"],
  },
  {
    group: "Skill",
    criterion: "Kỹ năng thiết lập mục tiêu",
    positions: ["Nhân viên điều phối Full - time"],
  },
  {
    group: "Skill",
    criterion: "Kỹ năng thấu hiểu nội tâm",
    positions: [],
  },
  {
    group: "Skill",
    criterion: "Kỹ năng ra quyết định",
    positions: ["Chuyên viên mua hàng", "Chuyên viên phân tích dữ liệu"],
  },
  {
    group: "Skill",
    criterion: "Kỹ năng phân tích dữ liệu",
    positions: [
      "Chuyên viên mua hàng",
      "Nhân viên phát triển sản phẩm",
      "Nhân viên điều phối Full - time",
      "Business Analyst",
      "Kế toán tổng hợp",
      "Kế toán thuế",
      "Chuyên viên phân tích dữ liệu",
      "Chuyên viên đào tạo và phát triển",
    ],
  },
  {
    group: "Skill",
    criterion: "Kỹ năng đàm phán, thuyết phục",
    positions: [
      "Chuyên viên mua hàng",
      "IT helpdesk",
      "Nhân viên kỹ thuật nội thất",
      "Nhân viên kỹ thuật điện nước",
      "Saleadmin",
      "Chuyên viên pháp chế",
      "Chuyên viên Tuyển dụng",
      "Chuyên viên nhân sự tổng hợp",
    ],
  },
  {
    group: "Skill",
    criterion: "Kỹ năng xử lý tình huống",
    positions: [
      "Chuyên viên mua hàng",
      "Nhân viên phát triển sản phẩm",
      "Quản lý vận hành kho",
      "Quản lý vận hành đóng gói",
      "Quản lý cơ sở",
      "Quản lý cơ sở fulltime",
      "Trưởng phòng kho vận",
      "IT helpdesk",
      "Nhân viên kỹ thuật nội thất",
      "Nhân viên kỹ thuật điện nước",
      "Saleadmin",
      "Visual Merchandiser",
      "Chuyên viên pháp chế",
      "Quản lý sản xuất bếp",
      "Chăm sóc khách hàng",
    ],
  },
  {
    group: "Skill",
    criterion: "Kỹ năng quản lý thời gian",
    positions: [
      "Chuyên viên mua hàng",
      "Nhân viên phát triển sản phẩm",
      "Graphic Designer",
      "Quản lý vận hành kho",
      "Quản lý vận hành đóng gói",
      "Trưởng phòng kho vận",
      "IT helpdesk",
      "Nhân viên kỹ thuật nội thất",
      "Nhân viên kỹ thuật điện nước",
      "Saleadmin",
      "Visual Merchandiser",
      "Business Analyst",
      "Kế toán thuế",
      "Chuyên viên pháp chế",
      "Quản lý sản xuất bếp",
      "Nhân viên giám sát chất lượng",
      "Kiểm toán viên nội bộ",
      "Chuyên viên Tuyển dụng",
      "Chuyên viên nhân sự tổng hợp",
    ],
  },
  {
    group: "Skill",
    criterion: "Kỹ năng lắng nghe",
    positions: [
      "Chuyên viên mua hàng",
      "Nhân viên phát triển sản phẩm",
      "Graphic Designer",
      "Business Analyst",
      "Chăm sóc khách hàng",
    ],
  },
  {
    group: "Skill",
    criterion: "Kỹ năng làm việc nhóm",
    positions: [
      "Chuyên viên mua hàng",
      "Nhân viên phát triển sản phẩm",
      "Graphic Designer",
      "Quản lý vận hành kho",
      "Quản lý vận hành đóng gói",
      "Quản lý cơ sở",
      "Quản lý cơ sở fulltime",
      "Trưởng phòng kho vận",
      "Visual Merchandiser",
      "Lập trình viên Full stack",
      "Quản lý sản xuất bếp",
      "Nhân viên giám sát chất lượng",
      "Kiểm toán viên nội bộ",
      "Chuyên viên Tuyển dụng",
      "Chuyên viên nhân sự tổng hợp",
    ],
  },
  {
    group: "Skill",
    criterion: "Kỹ năng tự học",
    positions: [
      "Chuyên viên mua hàng",
      "Nhân viên phát triển sản phẩm",
      "Graphic Designer",
      "IT helpdesk",
      "Nhân viên kỹ thuật nội thất",
      "Lập trình viên Full stack",
      "Nhân viên bếp fulltime",
      "Nhân viên giám sát chất lượng",
      "Kiểm toán viên nội bộ",
    ],
  },
  {
    group: "Skill",
    criterion: "Kỹ năng đối mặt với áp lực",
    positions: [
      "Graphic Designer",
      "Quản lý vận hành kho",
      "Quản lý vận hành đóng gói",
      "Trưởng phòng kho vận",
      "Lập trình viên Full stack",
      "Business Analyst",
      "Kế toán tổng hợp",
      "Kế toán thuế",
      "Nhân viên giám sát chất lượng",
    ],
  },
  {
    group: "Skill",
    criterion: "Kỹ năng giao tiếp",
    positions: [
      "Nhân viên phát triển sản phẩm",
      "Graphic Designer",
      "Quản lý vận hành kho",
      "Quản lý vận hành đóng gói",
      "Nhân viên điều phối Full - time",
      "Quản lý cơ sở",
      "Quản lý cơ sở fulltime",
      "Trưởng phòng kho vận",
      "IT helpdesk",
      "Nhân viên kỹ thuật nội thất",
      "Nhân viên kỹ thuật điện nước",
      "Saleadmin",
      "Lập trình viên Full stack",
      "Business Analyst",
      "Kế toán tổng hợp",
      "Chuyên viên phân tích dữ liệu",
      "Quản lý sản xuất bếp",
      "Nhân viên giám sát chất lượng",
      "Chăm sóc khách hàng",
      "Chuyên viên Tuyển dụng",
      "Chuyên viên nhân sự tổng hợp",
      "Chuyên viên đào tạo và phát triển",
    ],
  },
  {
    group: "Skill",
    criterion: "Kỹ năng xây dựng mỗi quan hệ",
    positions: ["Quản lý sản xuất bếp", "Chăm sóc khách hàng"],
  },
  {
    group: "Skill",
    criterion: "Kỹ năng quản lý xung đột",
    positions: ["Chăm sóc khách hàng"],
  },
  {
    group: "Skill",
    criterion: "Kỹ năng giải trình",
    positions: [
      "Nhân viên điều phối Full - time",
      "Quản lý cơ sở",
      "Quản lý cơ sở fulltime",
      "Business Analyst",
      "Chuyên viên phân tích dữ liệu",
      "Kiểm toán viên nội bộ",
      "Chăm sóc khách hàng",
    ],
  },
  {
    group: "Skill",
    criterion: "Kỹ năng quản trị rủi ro",
    positions: ["Chăm sóc khách hàng"],
  },
  {
    group: "Skill",
    criterion: "Kỹ năng quản trị mối quan hệ",
    positions: [],
  },
  {
    group: "Skill",
    criterion: "Kỹ năng đào tạo",
    positions: [
      "Quản lý cơ sở",
      "Quản lý cơ sở fulltime",
      "Quản lý sản xuất bếp",
      "Chuyên viên đào tạo và phát triển",
    ],
  },
  {
    group: "Skill",
    criterion: "Kỹ năng tư duy chiến lược",
    positions: ["Kiểm toán viên nội bộ"],
  },
  {
    group: "Skill",
    criterion: "Kỹ năng lập kế hoạch",
    positions: [
      "Trưởng phòng kho vận",
      "Business Analyst",
      "Kế toán thuế",
      "Chuyên viên đào tạo và phát triển",
    ],
  },
  {
    group: "Knowledge",
    criterion: "Khả năng tin học văn phòng",
    positions: [
      "Chuyên viên mua hàng",
      "Nhân viên phát triển sản phẩm",
      "Graphic Designer",
      "Quản lý vận hành kho",
      "Quản lý vận hành đóng gói",
      "Nhân viên điều phối Full - time",
      "Trưởng phòng kho vận",
      "IT helpdesk",
      "Visual Merchandiser",
      "Kế toán tổng hợp",
      "Kế toán thuế",
      "Chuyên viên phân tích dữ liệu",
      "Chuyên viên pháp chế",
      "Quản lý sản xuất bếp",
      "Kiểm toán viên nội bộ",
      "Chuyên viên nhân sự tổng hợp",
      "Chuyên viên đào tạo và phát triển",
    ],
  },
  {
    group: "Knowledge",
    criterion: "Khả năng sử dụng tiếng anh",
    positions: [
      "Chuyên viên mua hàng",
      "Nhân viên phát triển sản phẩm",
      "Graphic Designer",
      "IT helpdesk",
      "Lập trình viên Full stack",
      "Business Analyst",
    ],
  },
  {
    group: "Knowledge",
    criterion: "Kiến thức, các thuật ngữ chuyên ngành mua hàng",
    positions: ["Chuyên viên mua hàng"],
  },
  {
    group: "Knowledge",
    criterion: "Kiến thức về sản phẩm, ngành hàng, đối thủ",
    positions: [
      "Chuyên viên mua hàng",
      "Nhân viên điều phối Full - time",
      "Quản lý cơ sở",
      "Quản lý cơ sở fulltime",
      "Saleadmin",
    ],
  },
  {
    group: "Knowledge",
    criterion: "Am hiểu quy trình hệ thống nội bộ công ty",
    positions: [
      "Chuyên viên mua hàng",
      "Nhân viên điều phối Full - time",
      "Quản lý cơ sở",
      "Quản lý cơ sở fulltime",
      "Business Analyst",
      "Nhân viên giám sát chất lượng",
      "Kiểm toán viên nội bộ",
      "Chăm sóc khách hàng",
      "Chuyên viên Tuyển dụng",
      "Chuyên viên nhân sự tổng hợp",
      "Chuyên viên đào tạo và phát triển",
    ],
  },
  {
    group: "Knowledge",
    criterion: "Kiến thức về các loại nguyên liệu",
    positions: [
      "Nhân viên phát triển sản phẩm",
      "Quản lý vận hành kho",
      "Quản lý vận hành đóng gói",
      "Trưởng phòng kho vận",
      "Saleadmin",
      "Visual Merchandiser",
      "Business Analyst",
      "Chuyên viên phân tích dữ liệu",
      "Nhân viên bếp fulltime",
      "Chăm sóc khách hàng",
    ],
  },
  {
    group: "Knowledge",
    criterion: "Kiến thức về công nghệ thực phẩm",
    positions: [
      "Nhân viên phát triển sản phẩm",
      "Quản lý vận hành đóng gói",
      "Nhân viên bếp fulltime",
      "Nhân viên giám sát chất lượng",
    ],
  },
  {
    group: "Knowledge",
    criterion: "Kiến thức về sử dụng các công cụ, phần mềm thiết kế",
    positions: ["Graphic Designer", "Nhân viên kỹ thuật nội thất"],
  },
  {
    group: "Knowledge",
    criterion:
      "Kiến thức về chuyên ngành thiết kế (màu sắc, bố cục, hình ảnh, typo)",
    positions: [
      "Graphic Designer",
      "Nhân viên kỹ thuật nội thất",
      "Visual Merchandiser",
    ],
  },
  {
    group: "Knowledge",
    criterion: "Kiến thức về quy trình quản lý kho hàng",
    positions: ["Quản lý vận hành kho", "Trưởng phòng kho vận"],
  },
  {
    group: "Knowledge",
    criterion: "Kiến thức về thị trường vận tải ",
    positions: [
      "Nhân viên điều phối Full - time",
      "Trưởng phòng kho vận",
      "Saleadmin",
      "Chuyên viên phân tích dữ liệu",
    ],
  },
  {
    group: "Knowledge",
    criterion: "Kiến thức về bao bì đóng gói",
    positions: ["Quản lý vận hành đóng gói"],
  },
  {
    group: "Knowledge",
    criterion: "Kiến thức về thiết bị dụng cụ đóng gói thực phẩm",
    positions: ["Quản lý vận hành đóng gói"],
  },
  {
    group: "Knowledge",
    criterion: "Kiến thức về hệ thống máy tính",
    positions: ["IT helpdesk"],
  },
  {
    group: "Knowledge",
    criterion: "Kiến thức về hệ thống mạng internet",
    positions: ["IT helpdesk"],
  },
  {
    group: "Knowledge",
    criterion: "Kiến thức về kỹ thuật thi công nội thất cửa hàng",
    positions: ["Nhân viên kỹ thuật nội thất"],
  },
  {
    group: "Knowledge",
    criterion: "Kiến thức về kỹ thuật thi công quảng cáo cửa hàng",
    positions: ["Nhân viên kỹ thuật nội thất"],
  },
  {
    group: "Knowledge",
    criterion: "Kiến thức kỹ thuật điện",
    positions: ["Nhân viên kỹ thuật điện nước"],
  },
  {
    group: "Knowledge",
    criterion: "Kiến thức kỹ thuật cấp thoát nước",
    positions: ["Nhân viên kỹ thuật điện nước"],
  },
  {
    group: "Knowledge",
    criterion: "Kiến thức kĩ thuật điện lạnh",
    positions: ["Nhân viên kỹ thuật điện nước"],
  },
  {
    group: "Knowledge",
    criterion: "Kiến thức các loại hình POSM",
    positions: ["Visual Merchandiser"],
  },
  {
    group: "Knowledge",
    criterion: "Kiến thức về tiêu chuẩn lập trình",
    positions: ["Lập trình viên Full stack"],
  },
  {
    group: "Knowledge",
    criterion: "Kiến thức về UX/UI",
    positions: ["Lập trình viên Full stack"],
  },
  {
    group: "Knowledge",
    criterion: "Kiến thức quản trị server",
    positions: ["Lập trình viên Full stack"],
  },
  {
    group: "Knowledge",
    criterion: "Kiến thức về quy trình chuẩn: Agile, TOC",
    positions: ["Business Analyst"],
  },
  {
    group: "Knowledge",
    criterion: "Kiến thức lập trình Python",
    positions: ["Business Analyst"],
  },
  {
    group: "Knowledge",
    criterion: "Kiến thức về SQL và NoSQL",
    positions: ["Business Analyst"],
  },
  {
    group: "Knowledge",
    criterion: "Kiến thức nghiệp vụ kế toán",
    positions: ["Kế toán tổng hợp", "Kế toán thuế"],
  },
  {
    group: "Knowledge",
    criterion:
      "Am hiểu luật và chế độ kế toán liên quan mảng thuế trong doanh nghiệp",
    positions: ["Kế toán thuế"],
  },
  {
    group: "Knowledge",
    criterion: "Kiến thức về các bộ luật cơ bản có liên quan đến doanh nghiệp",
    positions: ["Chuyên viên pháp chế"],
  },
  {
    group: "Knowledge",
    criterion: "Biết cách tra cứu và ứng dụng văn bản luật ",
    positions: ["Kế toán thuế", "Chuyên viên pháp chế"],
  },
  {
    group: "Knowledge",
    criterion: "Khả năng sử dụng phần mềm kế toán",
    positions: ["Kế toán thuế"],
  },
  {
    group: "Knowledge",
    criterion: "Kiến thức về quy trình xử lý khiếu nại",
    positions: ["Chăm sóc khách hàng"],
  },
  {
    group: "Knowledge",
    criterion: "Kiến thức tâm lý học",
    positions: [
      "Chăm sóc khách hàng",
      "Chuyên viên Tuyển dụng",
      "Chuyên viên nhân sự tổng hợp",
    ],
  },
  {
    group: "Knowledge",
    criterion:
      "Kiến thức tiêu chuẩn vệ sinh thực phẩm trong lĩnh vực sản xuất và nhà hàng kinh doanh dịch vụ ăn uống",
    positions: [
      "Chuyên viên pháp chế",
      "Quản lý sản xuất bếp",
      "Nhân viên giám sát chất lượng",
    ],
  },
  {
    group: "Knowledge",
    criterion:
      "Kiến thức về quy trình vận hành và giám sát bếp chế biến công nghiệp",
    positions: ["Quản lý sản xuất bếp", "Nhân viên bếp fulltime"],
  },
  {
    group: "Knowledge",
    criterion: "Kiến thức về 7 công cụ quản lý chất lượng",
    positions: ["Nhân viên giám sát chất lượng"],
  },
  {
    group: "Knowledge",
    criterion: "Am hiểu về quy trình bộ phận giám sát",
    positions: ["Nhân viên giám sát chất lượng"],
  },
  {
    group: "Knowledge",
    criterion: "Am hiểu quy trình kiểm toán nội bộ",
    positions: ["Kiểm toán viên nội bộ"],
  },
  {
    group: "Knowledge",
    criterion: "Am hiểu quy trình vận hành hàng hóa nội bộ",
    positions: [
      "Nhân viên điều phối Full - time",
      "Quản lý cơ sở",
      "Quản lý cơ sở fulltime",
      "Chuyên viên pháp chế",
      "Kiểm toán viên nội bộ",
    ],
  },
  {
    group: "Knowledge",
    criterion: "Kiến thức chuyên môn nghiệp vụ nhân sự",
    positions: [
      "Chuyên viên Tuyển dụng",
      "Chuyên viên nhân sự tổng hợp",
      "Chuyên viên đào tạo và phát triển",
    ],
  },
  {
    group: "Knowledge",
    criterion: "Hiểu biết về thị trường & xu hướng tuyển dụng",
    positions: ["Chuyên viên Tuyển dụng", "Chuyên viên nhân sự tổng hợp"],
  },
  {
    group: "Knowledge",
    criterion: "Khả năng sử dụng ngôn ngữ",
    positions: [
      "Chuyên viên Tuyển dụng",
      "Chuyên viên nhân sự tổng hợp",
      "Chuyên viên đào tạo và phát triển",
    ],
  },
  {
    group: "Knowledge",
    criterion: "Kiến thức về sự phạm - Pedagogy",
    positions: ["Chuyên viên đào tạo và phát triển"],
  },
];
