export const users = [
  {
    code: "E09",
    displayName: "Chu Huy Thắng",
    departments: "Tech",
    email: "chuthang205@gmail.com",
    position: "Lập trình viên Full Stack",
  },
  {
    code: "D169",
    displayName: "Trương Thu Hằng",
    departments: "BS",
    email: "truongthuhang.28041998@gmail.com",
    position: "Business Analyst",
  },
  {
    code: "D2960",
    displayName: "Nguyễn Kiên Cường",
    departments: "Kiểm toán",
    email: "cuongnk12.mac@gmail.com",
    position: "Nhân viên kiểm toán",
  },
  {
    code: "D4309",
    displayName: "Nguyễn Văn Cương",
    departments: "Purchasing",
    email: "cuongnv.1512@gmail.com",
    position: "Chuyên viên phân tích dữ liệu",
  },
  {
    code: "D583",
    displayName: "Nguyễn Thế Anh",
    departments: "B1",
    email: "theanh2726@gmail.com",
    position: "Quản lý bếp",
  },
  {
    code: "D2663",
    displayName: "Nguyễn Phúc Tài",
    departments: "HR",
    email: "phuctai0810@gmail.com",
    position: "Nhân viên phát triển nhân sự",
  },
  {
    code: "D4163",
    displayName: "Lê Đăng Dũng",
    departments: "QC",
    email: "duongcongth@outlook.com.vn",
    position: "Nhân viên giám sát chất lượng",
  },
];

export const forms = [
  {
    title: "Lê Tuấn Hiệp",
    type: 1,
    position: "Legal",
    status: "pending",
    deadline: "2021-04-10",
    slug: "le-tuan-hiep",
    email: "hieptuanle@gmail.com",
  },
  {
    title: "Chu Huy Thắng",
    type: 2,
    position: "Tech Lead",
    status: "pending",
    deadline: "2021-04-10",
    slug: "chu-huy-thang",
    email: "chuthang205@gmail.com",
  },
  {
    title: "Trần Phương Anh",
    type: 3,
    position: "Quản lý kho",
    status: "pending",
    deadline: "2021-04-10",
    slug: "tran-phuong-anh",
    email: "tpa2498@gmail.com	",
  },
];

export const questions = [
  {
    positions: ["Tech Lead", "Quản lý kho"],
    content: "Phản hồi nhanh khi được hỏi?",
    group: "Attitue",
    layout: "Scale",
    type: 3,
  },
  {
    positions: ["Legal"],
    content: "Chăm chỉ và cố gắng?",
    group: "Attitue",
    layout: "Scale",
    type: 3,
  },
  {
    positions: ["Legal", "Tech Lead", "Quản lý kho"],
    content: "Có tinh thần chịu trách nhiệm khi mắc lỗi?",
    group: "Attitue",
    layout: "Scale",
    type: 3,
  },
  {
    positions: ["Quản lý kho"],
    content: "Khả năng đồng cảm?",
    group: "Attitue",
    layout: "Scale",
    type: 3,
  },
  {
    positions: ["Legal", "Tech Lead", "Quản lý kho"],
    content: "Kĩ năng tin học văn phòng?",
    group: "Skill",
    layout: "Text",
    type: 3,
  },
  {
    positions: ["Legal"],
    content: "Hiểu biết về luật?",
    group: "Knowledge",
    layout: "Text",
    type: 3,
  },
  {
    positions: ["Tech Lead"],
    content: "Hiểu biết Tech?",
    group: "Knowledge",
    layout: "Text",
    type: 3,
  },
  {
    positions: ["Quản lý kho"],
    content: "Hiểu biết kho?",
    group: "Knowledge",
    layout: "Text",
    type: 3,
  },
];
