import { computed, makeObservable, observable } from "mobx";
import { RootStore } from "./RootStore";
import * as urlSlug from "url-slug";
import { ReviewForm } from "./ReviewFormStore";

interface IndividualForm extends ReviewForm {
  reviewerCode: string;
  reviewerName: string;
}

export class IndividualFormStore {
  rootStore: RootStore;

  forms = forms;

  constructor(rootStore: RootStore) {
    this.rootStore = rootStore;

    makeObservable(this, {
      forms: observable,
      myForms: computed,
    });
  }

  get myForms() {
    // Nếu là BOM thì lấy hết tất cả form
    if (
      this.rootStore.authenticationStore.isBom &&
      this.rootStore.authenticationStore.seeAll
    )
      return this.forms;

    return this.forms.filter((form) => {
      return form.reviewerCode === this.rootStore.authenticationStore.userCode;
    });
  }
}

const forms = [
  {
    revieweeCode: "D583",
    revieweeName: "Nguyễn Thế Anh",
    reviewerCode: "D583",
    reviewerName: "Nguyễn Thế Anh",
    reviewType: 1,
  },
  {
    revieweeCode: "S306",
    revieweeName: "Nguyễn Thị Ngọc Anh",
    reviewerCode: "S306",
    reviewerName: "Nguyễn Thị Ngọc Anh",
    reviewType: 1,
  },
  {
    revieweeCode: "D1516",
    revieweeName: "Nguyễn Thùy Dương",
    reviewerCode: "D1516",
    reviewerName: "Nguyễn Thùy Dương",
    reviewType: 1,
  },
  {
    revieweeCode: "D2825",
    revieweeName: "Phạm Ngọc Quỳnh",
    reviewerCode: "D2825",
    reviewerName: "Phạm Ngọc Quỳnh",
    reviewType: 1,
  },
  {
    revieweeCode: "D4163",
    revieweeName: "Lê Đăng Dũng",
    reviewerCode: "D4163",
    reviewerName: "Lê Đăng Dũng",
    reviewType: 1,
  },
  {
    revieweeCode: "D5440",
    revieweeName: "Nguyễn Tuấn Anh",
    reviewerCode: "D5440",
    reviewerName: "Nguyễn Tuấn Anh",
    reviewType: 1,
  },
  {
    revieweeCode: "D327",
    revieweeName: "Dương Thị Nhung",
    reviewerCode: "D327",
    reviewerName: "Dương Thị Nhung",
    reviewType: 1,
  },
  {
    revieweeCode: "D169",
    revieweeName: "Trương Thu Hằng",
    reviewerCode: "D169",
    reviewerName: "Trương Thu Hằng",
    reviewType: 1,
  },
  {
    revieweeCode: "D708",
    revieweeName: "Đinh Phương Thảo",
    reviewerCode: "D708",
    reviewerName: "Đinh Phương Thảo",
    reviewType: 1,
  },
  {
    revieweeCode: "M30",
    revieweeName: "Lê Thị Mơ",
    reviewerCode: "M30",
    reviewerName: "Lê Thị Mơ",
    reviewType: 1,
  },
  {
    revieweeCode: "C037",
    revieweeName: "Nguyễn Thị Quỳnh",
    reviewerCode: "C037",
    reviewerName: "Nguyễn Thị Quỳnh",
    reviewType: 1,
  },
  {
    revieweeCode: "M63",
    revieweeName: "Trịnh Thị Hạnh Linh",
    reviewerCode: "M63",
    reviewerName: "Trịnh Thị Hạnh Linh",
    reviewType: 1,
  },
  {
    revieweeCode: "D2680",
    revieweeName: "Nguyễn Thị Diệp",
    reviewerCode: "D2680",
    reviewerName: "Nguyễn Thị Diệp",
    reviewType: 1,
  },
  {
    revieweeCode: "E09",
    revieweeName: "Chu Huy Thắng",
    reviewerCode: "E09",
    reviewerName: "Chu Huy Thắng",
    reviewType: 1,
  },
  {
    revieweeCode: "E62",
    revieweeName: "Nguyễn Xuân Trọng",
    reviewerCode: "E62",
    reviewerName: "Nguyễn Xuân Trọng",
    reviewType: 1,
  },
  {
    revieweeCode: "E65",
    revieweeName: "Lê Quang Thành",
    reviewerCode: "E65",
    reviewerName: "Lê Quang Thành",
    reviewType: 1,
  },
  {
    revieweeCode: "E80",
    revieweeName: "Nguyễn Mạnh Trường",
    reviewerCode: "E80",
    reviewerName: "Nguyễn Mạnh Trường",
    reviewType: 1,
  },
  {
    revieweeCode: "D79",
    revieweeName: "Nguyễn Thị Mỹ Linh",
    reviewerCode: "D79",
    reviewerName: "Nguyễn Thị Mỹ Linh",
    reviewType: 1,
  },
  {
    revieweeCode: "D2607",
    revieweeName: "Nguyễn Bá Nam",
    reviewerCode: "D2607",
    reviewerName: "Nguyễn Bá Nam",
    reviewType: 1,
  },
  {
    revieweeCode: "M38",
    revieweeName: "Phạm Ngọc Quỳnh",
    reviewerCode: "M38",
    reviewerName: "Phạm Ngọc Quỳnh",
    reviewType: 1,
  },
  {
    revieweeCode: "S146",
    revieweeName: "Bùi Văn Vương",
    reviewerCode: "S146",
    reviewerName: "Bùi Văn Vương",
    reviewType: 1,
  },
  {
    revieweeCode: "D2537",
    revieweeName: "Nguyễn Văn Thao",
    reviewerCode: "D2537",
    reviewerName: "Nguyễn Văn Thao",
    reviewType: 1,
  },
  {
    revieweeCode: "E73",
    revieweeName: "Nguyễn Anh Tú",
    reviewerCode: "E73",
    reviewerName: "Nguyễn Anh Tú",
    reviewType: 1,
  },
  {
    revieweeCode: "D388",
    revieweeName: "Trần Phương Anh",
    reviewerCode: "D388",
    reviewerName: "Trần Phương Anh",
    reviewType: 1,
  },
  {
    revieweeCode: "D3982",
    revieweeName: "Hoàng Văn Luýt",
    reviewerCode: "D3982",
    reviewerName: "Hoàng Văn Luýt",
    reviewType: 1,
  },
  {
    revieweeCode: "D93",
    revieweeName: "Nguyễn Thúy Vi",
    reviewerCode: "D93",
    reviewerName: "Nguyễn Thúy Vi",
    reviewType: 1,
  },
  {
    revieweeCode: "S41",
    revieweeName: "Nguyễn Hữu Long",
    reviewerCode: "S41",
    reviewerName: "Nguyễn Hữu Long",
    reviewType: 1,
  },
  {
    revieweeCode: "D557",
    revieweeName: "Vũ Thị Lành",
    reviewerCode: "D557",
    reviewerName: "Vũ Thị Lành",
    reviewType: 1,
  },
  {
    revieweeCode: "D479",
    revieweeName: "Nguyễn Minh Ngọc",
    reviewerCode: "D479",
    reviewerName: "Nguyễn Minh Ngọc",
    reviewType: 1,
  },
  {
    revieweeCode: "S78",
    revieweeName: "Bùi Thị Hương",
    reviewerCode: "S78",
    reviewerName: "Bùi Thị Hương",
    reviewType: 1,
  },
  {
    revieweeCode: "D5093",
    revieweeName: "Nguyễn Kim Hưng",
    reviewerCode: "D5093",
    reviewerName: "Nguyễn Kim Hưng",
    reviewType: 1,
  },
  {
    revieweeCode: "D337",
    revieweeName: "Nguyễn Thành Nam",
    reviewerCode: "D337",
    reviewerName: "Nguyễn Thành Nam",
    reviewType: 1,
  },
  {
    revieweeCode: "S110",
    revieweeName: "Nguyễn Văn Việt",
    reviewerCode: "S110",
    reviewerName: "Nguyễn Văn Việt",
    reviewType: 1,
  },
  {
    revieweeCode: "M70",
    revieweeName: "Phạm Khánh Linh",
    reviewerCode: "M70",
    reviewerName: "Phạm Khánh Linh",
    reviewType: 1,
  },
  {
    revieweeCode: "D583",
    revieweeName: "Nguyễn Thế Anh",
    reviewerCode: "D337",
    reviewerName: "Nguyễn Thành Nam",
    reviewType: 2,
  },
  {
    revieweeCode: "S306",
    revieweeName: "Nguyễn Thị Ngọc Anh",
    reviewerCode: "E09",
    reviewerName: "Chu Huy Thắng",
    reviewType: 2,
  },
  {
    revieweeCode: "D1516",
    revieweeName: "Nguyễn Thùy Dương",
    reviewerCode: "D583",
    reviewerName: "Nguyễn Thế Anh",
    reviewType: 2,
  },
  {
    revieweeCode: "D2825",
    revieweeName: "Phạm Ngọc Quỳnh",
    reviewerCode: "D1516",
    reviewerName: "Nguyễn Thùy Dương",
    reviewType: 2,
  },
  {
    revieweeCode: "D4163",
    revieweeName: "Lê Đăng Dũng",
    reviewerCode: "M38",
    reviewerName: "Phạm Ngọc Quỳnh - Ship",
    reviewType: 2,
  },
  {
    revieweeCode: "D5440",
    revieweeName: "Nguyễn Tuấn Anh",
    reviewerCode: "D1516",
    reviewerName: "Nguyễn Thùy Dương",
    reviewType: 2,
  },
  {
    revieweeCode: "D327",
    revieweeName: "Dương Thị Nhung",
    reviewerCode: "D583",
    reviewerName: "Nguyễn Thế Anh",
    reviewType: 2,
  },
  {
    revieweeCode: "D169",
    revieweeName: "Trương Thu Hằng",
    reviewerCode: "E62",
    reviewerName: "Vũ Xuân Trọng",
    reviewType: 2,
  },
  {
    revieweeCode: "D708",
    revieweeName: "Đinh Phương Thảo",
    reviewerCode: "D169",
    reviewerName: "Trương Thu Hằng",
    reviewType: 2,
  },
  {
    revieweeCode: "M30",
    revieweeName: "Lê Thị Mơ",
    reviewerCode: "D2607",
    reviewerName: "Nguyễn Bá Nam",
    reviewType: 2,
  },
  {
    revieweeCode: "C037",
    revieweeName: "Nguyễn Thị Quỳnh",
    reviewerCode: "D992",
    reviewerName: "Lê Thị Ngọc Ánh",
    reviewType: 2,
  },
  {
    revieweeCode: "M63",
    revieweeName: "Trịnh Thị Hạnh Linh",
    reviewerCode: "C037",
    reviewerName: "Nguyễn Thị Quỳnh",
    reviewType: 2,
  },
  {
    revieweeCode: "D2680",
    revieweeName: "Nguyễn Thị Diệp",
    reviewerCode: "M70",
    reviewerName: "Phạm Khánh Linh",
    reviewType: 2,
  },
  {
    revieweeCode: "E09",
    revieweeName: "Chu Huy Thắng",
    reviewerCode: "D169",
    reviewerName: "Trương Thu Hằng",
    reviewType: 2,
  },
  {
    revieweeCode: "E62",
    revieweeName: "Nguyễn Xuân Trọng",
    reviewerCode: "D169",
    reviewerName: "Trương Thu Hằng",
    reviewType: 2,
  },
  {
    revieweeCode: "E65",
    revieweeName: "Lê Quang Thành",
    reviewerCode: "E09",
    reviewerName: "Chu Huy Thắng",
    reviewType: 2,
  },
  {
    revieweeCode: "E80",
    revieweeName: "Nguyễn Mạnh Trường",
    reviewerCode: "E09",
    reviewerName: "Chu Huy Thắng",
    reviewType: 2,
  },
  {
    revieweeCode: "D79",
    revieweeName: "Nguyễn Thị Mỹ Linh",
    reviewerCode: "D479",
    reviewerName: "Nguyễn Minh Ngọc",
    reviewType: 2,
  },
  {
    revieweeCode: "D2607",
    revieweeName: "Nguyễn Bá Nam",
    reviewerCode: "S363",
    reviewerName: "Vương Thị Hương Ly",
    reviewType: 2,
  },
  {
    revieweeCode: "M38",
    revieweeName: "Phạm Ngọc Quỳnh",
    reviewerCode: "M70",
    reviewerName: "Phạm Khánh Linh",
    reviewType: 2,
  },
  {
    revieweeCode: "S146",
    revieweeName: "Bùi Văn Vương",
    reviewerCode: "E73",
    reviewerName: "Nguyễn Anh Tú",
    reviewType: 2,
  },
  {
    revieweeCode: "D2537",
    revieweeName: "Nguyễn Văn Thao",
    reviewerCode: "D583",
    reviewerName: "Nguyễn Thế Anh",
    reviewType: 2,
  },
  {
    revieweeCode: "E73",
    revieweeName: "Nguyễn Anh Tú",
    reviewerCode: "D2537",
    reviewerName: "Nguyễn Văn Thao",
    reviewType: 2,
  },
  {
    revieweeCode: "D388",
    revieweeName: "Trần Phương Anh",
    reviewerCode: "D557",
    reviewerName: "Vũ Thị Lành",
    reviewType: 2,
  },
  {
    revieweeCode: "D3982",
    revieweeName: "Hoàng Văn Luýt",
    reviewerCode: "D2663",
    reviewerName: "Nguyễn Phúc Tài",
    reviewType: 2,
  },
  {
    revieweeCode: "D93",
    revieweeName: "Nguyễn Thúy Vi",
    reviewerCode: "S146",
    reviewerName: "Bùi Văn Vương",
    reviewType: 2,
  },
  {
    revieweeCode: "S41",
    revieweeName: "Nguyễn Hữu Long",
    reviewerCode: "E73",
    reviewerName: "Nguyễn Anh Tú",
    reviewType: 2,
  },
  {
    revieweeCode: "D557",
    revieweeName: "Vũ Thị Lành",
    reviewerCode: "D992",
    reviewerName: "Lê Thị Ngọc Ánh",
    reviewType: 2,
  },
  {
    revieweeCode: "D479",
    revieweeName: "Nguyễn Minh Ngọc",
    reviewerCode: "D2464",
    reviewerName: "Hoàng Thị Thanh Hằng",
    reviewType: 2,
  },
  {
    revieweeCode: "S78",
    revieweeName: "Bùi Thị Hương",
    reviewerCode: "S306",
    reviewerName: "Nguyễn Thị Ngọc Anh",
    reviewType: 2,
  },
  {
    revieweeCode: "D5093",
    revieweeName: "Nguyễn Kim Hưng",
    reviewerCode: "M70",
    reviewerName: "Phạm Khánh Linh",
    reviewType: 2,
  },
  {
    revieweeCode: "D337",
    revieweeName: "Nguyễn Thành Nam",
    reviewerCode: "D583",
    reviewerName: "Nguyễn Thế Anh",
    reviewType: 2,
  },
  {
    revieweeCode: "S110",
    revieweeName: "Nguyễn Văn Việt",
    reviewerCode: "D557",
    reviewerName: "Vũ Thị Lành",
    reviewType: 2,
  },
  {
    revieweeCode: "M70",
    revieweeName: "Phạm Khánh Linh",
    reviewerCode: "D992",
    reviewerName: "Lê Thị Ngọc Ánh",
    reviewType: 2,
  },
  {
    revieweeCode: "D583",
    revieweeName: "Nguyễn Thế Anh",
    reviewerCode: "D2607",
    reviewerName: "Nguyễn Bá Nam",
    reviewType: 2,
  },
  {
    revieweeCode: "S306",
    revieweeName: "Nguyễn Thị Ngọc Anh",
    reviewerCode: "D169",
    reviewerName: "Trương Thu Hằng",
    reviewType: 2,
  },
  {
    revieweeCode: "D1516",
    revieweeName: "Nguyễn Thùy Dương",
    reviewerCode: "D337",
    reviewerName: "Nguyễn Thành Nam",
    reviewType: 2,
  },
  {
    revieweeCode: "D2825",
    revieweeName: "Phạm Ngọc Quỳnh",
    reviewerCode: "E73",
    reviewerName: "Nguyễn Anh Tú",
    reviewType: 2,
  },
  {
    revieweeCode: "D4163",
    revieweeName: "Lê Đăng Dũng",
    reviewerCode: "D1516",
    reviewerName: "Nguyễn Thùy Dương",
    reviewType: 2,
  },
  {
    revieweeCode: "D5440",
    revieweeName: "Nguyễn Tuấn Anh",
    reviewerCode: "D2537",
    reviewerName: "Nguyễn Văn Thao",
    reviewType: 2,
  },
  {
    revieweeCode: "D327",
    revieweeName: "Dương Thị Nhung",
    reviewerCode: "D1516",
    reviewerName: "Nguyễn Thùy Dương",
    reviewType: 2,
  },
  {
    revieweeCode: "D169",
    revieweeName: "Trương Thu Hằng",
    reviewerCode: "C037",
    reviewerName: "Nguyễn Thị Quỳnh",
    reviewType: 2,
  },
  {
    revieweeCode: "D708",
    revieweeName: "Đinh Phương Thảo",
    reviewerCode: "S306",
    reviewerName: "Nguyễn Thị Ngọc Anh",
    reviewType: 2,
  },
  {
    revieweeCode: "M30",
    revieweeName: "Lê Thị Mơ",
    reviewerCode: "D2464",
    reviewerName: "Hoàng Thị Thanh Hằng",
    reviewType: 2,
  },
  {
    revieweeCode: "C037",
    revieweeName: "Nguyễn Thị Quỳnh",
    reviewerCode: "D169",
    reviewerName: "Trương Thu Hằng",
    reviewType: 2,
  },
  {
    revieweeCode: "M63",
    revieweeName: "Trịnh Thị Hạnh Linh",
    reviewerCode: "M38",
    reviewerName: "Phạm Ngọc Quỳnh - Ship",
    reviewType: 2,
  },
  {
    revieweeCode: "D2680",
    revieweeName: "Nguyễn Thị Diệp",
    reviewerCode: "D4309",
    reviewerName: "Nguyễn Văn Cương",
    reviewType: 2,
  },
  {
    revieweeCode: "E09",
    revieweeName: "Chu Huy Thắng",
    reviewerCode: "E62",
    reviewerName: "Vũ Xuân Trọng",
    reviewType: 2,
  },
  {
    revieweeCode: "E62",
    revieweeName: "Nguyễn Xuân Trọng",
    reviewerCode: "E09",
    reviewerName: "Chu Huy Thắng",
    reviewType: 2,
  },
  {
    revieweeCode: "E65",
    revieweeName: "Lê Quang Thành",
    reviewerCode: "S110",
    reviewerName: "Nguyễn Văn Việt",
    reviewType: 2,
  },
  {
    revieweeCode: "E80",
    revieweeName: "Nguyễn Mạnh Trường",
    reviewerCode: "M48",
    reviewerName: "Lê Thùy Linh",
    reviewType: 2,
  },
  {
    revieweeCode: "D79",
    revieweeName: "Nguyễn Thị Mỹ Linh",
    reviewerCode: "D2464",
    reviewerName: "Hoàng Thị Thanh Hằng",
    reviewType: 2,
  },
  {
    revieweeCode: "D2607",
    revieweeName: "Nguyễn Bá Nam",
    reviewerCode: "M30",
    reviewerName: "Lê Thị Mơ",
    reviewType: 2,
  },
  {
    revieweeCode: "M38",
    revieweeName: "Phạm Ngọc Quỳnh",
    reviewerCode: "D5093",
    reviewerName: "Nguyễn Kim Hưng",
    reviewType: 2,
  },
  {
    revieweeCode: "S146",
    revieweeName: "Bùi Văn Vương",
    reviewerCode: "D93",
    reviewerName: "Nguyễn Thúy Vi",
    reviewType: 2,
  },
  {
    revieweeCode: "D2537",
    revieweeName: "Nguyễn Văn Thao",
    reviewerCode: "C037",
    reviewerName: "Nguyễn Thị Quỳnh",
    reviewType: 2,
  },
  {
    revieweeCode: "E73",
    revieweeName: "Nguyễn Anh Tú",
    reviewerCode: "C037",
    reviewerName: "Nguyễn Thị Quỳnh",
    reviewType: 2,
  },
  {
    revieweeCode: "D388",
    revieweeName: "Trần Phương Anh",
    reviewerCode: "D5093",
    reviewerName: "Nguyễn Kim Hưng",
    reviewType: 2,
  },
  {
    revieweeCode: "D3982",
    revieweeName: "Hoàng Văn Luýt",
    reviewerCode: "D1886",
    reviewerName: "Phùng Thị Ngọc Tuyết",
    reviewType: 2,
  },
  {
    revieweeCode: "D93",
    revieweeName: "Nguyễn Thúy Vi",
    reviewerCode: "E73",
    reviewerName: "Nguyễn Anh Tú",
    reviewType: 2,
  },
  {
    revieweeCode: "S41",
    revieweeName: "Nguyễn Hữu Long",
    reviewerCode: "D5093",
    reviewerName: "Nguyễn Kim Hưng",
    reviewType: 2,
  },
  {
    revieweeCode: "D557",
    revieweeName: "Vũ Thị Lành",
    reviewerCode: "S306",
    reviewerName: "Nguyễn Thị Ngọc Anh",
    reviewType: 2,
  },
  {
    revieweeCode: "D479",
    revieweeName: "Nguyễn Minh Ngọc",
    reviewerCode: "D79",
    reviewerName: "Nguyễn Thị Mỹ Linh",
    reviewType: 2,
  },
  {
    revieweeCode: "S78",
    revieweeName: "Bùi Thị Hương",
    reviewerCode: "D2960",
    reviewerName: "Nguyễn Kiên Cường",
    reviewType: 2,
  },
  {
    revieweeCode: "D5093",
    revieweeName: "Nguyễn Kim Hưng",
    reviewerCode: "S306",
    reviewerName: "Nguyễn Thị Ngọc Anh",
    reviewType: 2,
  },
  {
    revieweeCode: "D337",
    revieweeName: "Nguyễn Thành Nam",
    reviewerCode: "D1334",
    reviewerName: "Hà Thị Lan Nhi",
    reviewType: 2,
  },
  {
    revieweeCode: "S110",
    revieweeName: "Nguyễn Văn Việt",
    reviewerCode: "D337",
    reviewerName: "Nguyễn Thành Nam",
    reviewType: 2,
  },
  {
    revieweeCode: "M70",
    revieweeName: "Phạm Khánh Linh",
    reviewerCode: "S41",
    reviewerName: "Nguyễn Hữu Long",
    reviewType: 2,
  },
  {
    revieweeCode: "D583",
    revieweeName: "Nguyễn Thế Anh",
    reviewerCode: "D992",
    reviewerName: "Lê Thị Ngọc Ánh",
    reviewType: 2,
  },
  {
    revieweeCode: "S306",
    revieweeName: "Nguyễn Thị Ngọc Anh",
    reviewerCode: "S78",
    reviewerName: "Bùi Thị Hương",
    reviewType: 2,
  },
  {
    revieweeCode: "D1516",
    revieweeName: "Nguyễn Thùy Dương",
    reviewerCode: "D557",
    reviewerName: "Vũ Thị Lành",
    reviewType: 2,
  },
  {
    revieweeCode: "D2825",
    revieweeName: "Phạm Ngọc Quỳnh",
    reviewerCode: "D2680",
    reviewerName: "Nguyễn Thị Diệp",
    reviewType: 2,
  },
  {
    revieweeCode: "D4163",
    revieweeName: "Lê Đăng Dũng",
    reviewerCode: "M70",
    reviewerName: "Phạm Khánh Linh",
    reviewType: 2,
  },
  {
    revieweeCode: "D5440",
    revieweeName: "Nguyễn Tuấn Anh",
    reviewerCode: "E09",
    reviewerName: "Chu Huy Thắng",
    reviewType: 2,
  },
  {
    revieweeCode: "D327",
    revieweeName: "Dương Thị Nhung",
    reviewerCode: "M30",
    reviewerName: "Lê Thị Mơ",
    reviewType: 2,
  },
  {
    revieweeCode: "D169",
    revieweeName: "Trương Thu Hằng",
    reviewerCode: "D02",
    reviewerName: "Nguyễn Thu Thảo",
    reviewType: 2,
  },
  {
    revieweeCode: "D708",
    revieweeName: "Đinh Phương Thảo",
    reviewerCode: "M70",
    reviewerName: "Phạm Khánh Linh",
    reviewType: 2,
  },
  {
    revieweeCode: "M30",
    revieweeName: "Lê Thị Mơ",
    reviewerCode: "D169",
    reviewerName: "Trương Thu Hằng",
    reviewType: 2,
  },
  {
    revieweeCode: "C037",
    revieweeName: "Nguyễn Thị Quỳnh",
    reviewerCode: "S363",
    reviewerName: "Vương Thị Hương Ly",
    reviewType: 2,
  },
  {
    revieweeCode: "M63",
    revieweeName: "Trịnh Thị Hạnh Linh",
    reviewerCode: "D02",
    reviewerName: "Nguyễn Thu Thảo",
    reviewType: 2,
  },
  {
    revieweeCode: "D2680",
    revieweeName: "Nguyễn Thị Diệp",
    reviewerCode: "D2825",
    reviewerName: "Phạm Ngọc Quỳnh - QC",
    reviewType: 2,
  },
  {
    revieweeCode: "E09",
    revieweeName: "Chu Huy Thắng",
    reviewerCode: "S306",
    reviewerName: "Nguyễn Thị Ngọc Anh",
    reviewType: 2,
  },
  {
    revieweeCode: "E62",
    revieweeName: "Nguyễn Xuân Trọng",
    reviewerCode: "D994",
    reviewerName: "Đỗ Vũ Thúy Hòa",
    reviewType: 2,
  },
  {
    revieweeCode: "E65",
    revieweeName: "Lê Quang Thành",
    reviewerCode: "D994",
    reviewerName: "Đỗ Vũ Thúy Hòa",
    reviewType: 2,
  },
  {
    revieweeCode: "E80",
    revieweeName: "Nguyễn Mạnh Trường",
    reviewerCode: "D1516",
    reviewerName: "Nguyễn Thùy Dương",
    reviewType: 2,
  },
  {
    revieweeCode: "D79",
    revieweeName: "Nguyễn Thị Mỹ Linh",
    reviewerCode: "D1516",
    reviewerName: "Nguyễn Thùy Dương",
    reviewType: 2,
  },
  {
    revieweeCode: "D2607",
    revieweeName: "Nguyễn Bá Nam",
    reviewerCode: "D994",
    reviewerName: "Đỗ Vũ Thúy Hòa",
    reviewType: 2,
  },
  {
    revieweeCode: "M38",
    revieweeName: "Phạm Ngọc Quỳnh",
    reviewerCode: "S306",
    reviewerName: "Nguyễn Thị Ngọc Anh",
    reviewType: 2,
  },
  {
    revieweeCode: "S146",
    revieweeName: "Bùi Văn Vương",
    reviewerCode: "D3793",
    reviewerName: "Trương Văn Vỹ",
    reviewType: 2,
  },
  {
    revieweeCode: "D2537",
    revieweeName: "Nguyễn Văn Thao",
    reviewerCode: "D5440",
    reviewerName: "Nguyễn Tuấn Anh",
    reviewType: 2,
  },
  {
    revieweeCode: "E73",
    revieweeName: "Nguyễn Anh Tú",
    reviewerCode: "D1516",
    reviewerName: "Nguyễn Thùy Dương",
    reviewType: 2,
  },
  {
    revieweeCode: "D388",
    revieweeName: "Trần Phương Anh",
    reviewerCode: "E09",
    reviewerName: "Chu Huy Thắng",
    reviewType: 2,
  },
  {
    revieweeCode: "D3982",
    revieweeName: "Hoàng Văn Luýt",
    reviewerCode: "D2680",
    reviewerName: "Nguyễn Thị Diệp",
    reviewType: 2,
  },
  {
    revieweeCode: "D93",
    revieweeName: "Nguyễn Thúy Vi",
    reviewerCode: "D79",
    reviewerName: "Nguyễn Thị Mỹ Linh",
    reviewType: 2,
  },
  {
    revieweeCode: "S41",
    revieweeName: "Nguyễn Hữu Long",
    reviewerCode: "C037",
    reviewerName: "Nguyễn Thị Quỳnh",
    reviewType: 2,
  },
  {
    revieweeCode: "D557",
    revieweeName: "Vũ Thị Lành",
    reviewerCode: "E73",
    reviewerName: "Nguyễn Anh Tú",
    reviewType: 2,
  },
  {
    revieweeCode: "D479",
    revieweeName: "Nguyễn Minh Ngọc",
    reviewerCode: "D2607",
    reviewerName: "Nguyễn Bá Nam",
    reviewType: 2,
  },
  {
    revieweeCode: "S78",
    revieweeName: "Bùi Thị Hương",
    reviewerCode: "D02",
    reviewerName: "Nguyễn Thu Thảo",
    reviewType: 2,
  },
  {
    revieweeCode: "D5093",
    revieweeName: "Nguyễn Kim Hưng",
    reviewerCode: "D02",
    reviewerName: "Nguyễn Thu Thảo",
    reviewType: 2,
  },
  {
    revieweeCode: "D337",
    revieweeName: "Nguyễn Thành Nam",
    reviewerCode: "D2825",
    reviewerName: "Phạm Ngọc Quỳnh - QC",
    reviewType: 2,
  },
  {
    revieweeCode: "S110",
    revieweeName: "Nguyễn Văn Việt",
    reviewerCode: "E09",
    reviewerName: "Chu Huy Thắng",
    reviewType: 2,
  },
  {
    revieweeCode: "M70",
    revieweeName: "Phạm Khánh Linh",
    reviewerCode: "C037",
    reviewerName: "Nguyễn Thị Quỳnh",
    reviewType: 2,
  },
  {
    revieweeCode: "D583",
    revieweeName: "Nguyễn Thế Anh",
    reviewerCode: "D1516",
    reviewerName: "Nguyễn Thùy Dương",
    reviewType: 2,
  },
  {
    revieweeCode: "S306",
    revieweeName: "Nguyễn Thị Ngọc Anh",
    reviewerCode: "D2960",
    reviewerName: "Nguyễn Kiên Cường",
    reviewType: 2,
  },
  {
    revieweeCode: "D1516",
    revieweeName: "Nguyễn Thùy Dương",
    reviewerCode: "D4163",
    reviewerName: "Lê Đăng Dũng",
    reviewType: 2,
  },
  {
    revieweeCode: "D2825",
    revieweeName: "Phạm Ngọc Quỳnh",
    reviewerCode: "D4309",
    reviewerName: "Nguyễn Văn Cương",
    reviewType: 2,
  },
  {
    revieweeCode: "D4163",
    revieweeName: "Lê Đăng Dũng",
    reviewerCode: "D352",
    reviewerName: "Hoàng Thị Dịu",
    reviewType: 2,
  },
  {
    revieweeCode: "D5440",
    revieweeName: "Nguyễn Tuấn Anh",
    reviewerCode: "D93",
    reviewerName: "Nguyễn Thúy Vi",
    reviewType: 2,
  },
  {
    revieweeCode: "D327",
    revieweeName: "Dương Thị Nhung",
    reviewerCode: "D2607",
    reviewerName: "Nguyễn Bá Nam",
    reviewType: 2,
  },
  {
    revieweeCode: "D169",
    revieweeName: "Trương Thu Hằng",
    reviewerCode: "D708",
    reviewerName: "Đinh Phương Thảo",
    reviewType: 2,
  },
  {
    revieweeCode: "D708",
    revieweeName: "Đinh Phương Thảo",
    reviewerCode: "D557",
    reviewerName: "Vũ Thị Lành",
    reviewType: 2,
  },
  {
    revieweeCode: "M30",
    revieweeName: "Lê Thị Mơ",
    reviewerCode: "S363",
    reviewerName: "Vương Thị Hương Ly",
    reviewType: 2,
  },
  {
    revieweeCode: "C037",
    revieweeName: "Nguyễn Thị Quỳnh",
    reviewerCode: "S306",
    reviewerName: "Nguyễn Thị Ngọc Anh",
    reviewType: 2,
  },
  {
    revieweeCode: "M63",
    revieweeName: "Trịnh Thị Hạnh Linh",
    reviewerCode: "E65",
    reviewerName: "Lê Quang Thành",
    reviewType: 2,
  },
  {
    revieweeCode: "D2680",
    revieweeName: "Nguyễn Thị Diệp",
    reviewerCode: "D3982",
    reviewerName: "Hoàng Văn Luýt",
    reviewType: 2,
  },
  {
    revieweeCode: "E09",
    revieweeName: "Chu Huy Thắng",
    reviewerCode: "D327",
    reviewerName: "Dương Thị Nhung",
    reviewType: 2,
  },
  {
    revieweeCode: "E62",
    revieweeName: "Nguyễn Xuân Trọng",
    reviewerCode: "M63",
    reviewerName: "Trịnh Thị Hạnh Linh",
    reviewType: 2,
  },
  {
    revieweeCode: "E65",
    revieweeName: "Lê Quang Thành",
    reviewerCode: "D1516",
    reviewerName: "Nguyễn Thùy Dương",
    reviewType: 2,
  },
  {
    revieweeCode: "E80",
    revieweeName: "Nguyễn Mạnh Trường",
    reviewerCode: "D708",
    reviewerName: "Đinh Phương Thảo",
    reviewType: 2,
  },
  {
    revieweeCode: "D79",
    revieweeName: "Nguyễn Thị Mỹ Linh",
    reviewerCode: "D2607",
    reviewerName: "Nguyễn Bá Nam",
    reviewType: 2,
  },
  {
    revieweeCode: "D2607",
    revieweeName: "Nguyễn Bá Nam",
    reviewerCode: "D79",
    reviewerName: "Nguyễn Thị Mỹ Linh",
    reviewType: 2,
  },
  {
    revieweeCode: "M38",
    revieweeName: "Phạm Ngọc Quỳnh",
    reviewerCode: "D4163",
    reviewerName: "Lê Đăng Dũng",
    reviewType: 2,
  },
  {
    revieweeCode: "D2537",
    revieweeName: "Nguyễn Văn Thao",
    reviewerCode: "E73",
    reviewerName: "Nguyễn Anh Tú",
    reviewType: 2,
  },
  {
    revieweeCode: "E73",
    revieweeName: "Nguyễn Anh Tú",
    reviewerCode: "E09",
    reviewerName: "Chu Huy Thắng",
    reviewType: 2,
  },
  {
    revieweeCode: "D388",
    revieweeName: "Trần Phương Anh",
    reviewerCode: "D169",
    reviewerName: "Trương Thu Hằng",
    reviewType: 2,
  },
  {
    revieweeCode: "D3982",
    revieweeName: "Hoàng Văn Luýt",
    reviewerCode: "E73",
    reviewerName: "Nguyễn Anh Tú",
    reviewType: 2,
  },
  {
    revieweeCode: "D93",
    revieweeName: "Nguyễn Thúy Vi",
    reviewerCode: "D2772",
    reviewerName: "Đào Thị Khánh Huyền",
    reviewType: 2,
  },
  {
    revieweeCode: "S41",
    revieweeName: "Nguyễn Hữu Long",
    reviewerCode: "D2680",
    reviewerName: "Nguyễn Thị Diệp",
    reviewType: 2,
  },
  {
    revieweeCode: "D557",
    revieweeName: "Vũ Thị Lành",
    reviewerCode: "D708",
    reviewerName: "Đinh Phương Thảo",
    reviewType: 2,
  },
  {
    revieweeCode: "D479",
    revieweeName: "Nguyễn Minh Ngọc",
    reviewerCode: "M30",
    reviewerName: "Lê Thị Mơ",
    reviewType: 2,
  },
  {
    revieweeCode: "S78",
    revieweeName: "Bùi Thị Hương",
    reviewerCode: "C037",
    reviewerName: "Nguyễn Thị Quỳnh",
    reviewType: 2,
  },
  {
    revieweeCode: "D5093",
    revieweeName: "Nguyễn Kim Hưng",
    reviewerCode: "D169",
    reviewerName: "Trương Thu Hằng",
    reviewType: 2,
  },
  {
    revieweeCode: "D337",
    revieweeName: "Nguyễn Thành Nam",
    reviewerCode: "D79",
    reviewerName: "Nguyễn Thị Mỹ Linh",
    reviewType: 2,
  },
  {
    revieweeCode: "S110",
    revieweeName: "Nguyễn Văn Việt",
    reviewerCode: "M48",
    reviewerName: "Lê Thùy Linh",
    reviewType: 2,
  },
  {
    revieweeCode: "M70",
    revieweeName: "Phạm Khánh Linh",
    reviewerCode: "D2680",
    reviewerName: "Nguyễn Thị Diệp",
    reviewType: 2,
  },
  {
    revieweeCode: "D583",
    revieweeName: "Nguyễn Thế Anh",
    reviewerCode: "D703",
    reviewerName: "Nguyễn Huyền Trang",
    reviewType: 2,
  },
  {
    revieweeCode: "S306",
    revieweeName: "Nguyễn Thị Ngọc Anh",
    reviewerCode: "D992",
    reviewerName: "Lê Thị Ngọc Ánh",
    reviewType: 2,
  },
  {
    revieweeCode: "D1516",
    revieweeName: "Nguyễn Thùy Dương",
    reviewerCode: "E73",
    reviewerName: "Nguyễn Anh Tú",
    reviewType: 2,
  },
  {
    revieweeCode: "D2825",
    revieweeName: "Phạm Ngọc Quỳnh",
    reviewerCode: "D5093",
    reviewerName: "Nguyễn Kim Hưng",
    reviewType: 2,
  },
  {
    revieweeCode: "D4163",
    revieweeName: "Lê Đăng Dũng",
    reviewerCode: "D93",
    reviewerName: "Nguyễn Thúy Vi",
    reviewType: 2,
  },
  {
    revieweeCode: "D5440",
    revieweeName: "Nguyễn Tuấn Anh",
    reviewerCode: "D2607",
    reviewerName: "Nguyễn Bá Nam",
    reviewType: 2,
  },
  {
    revieweeCode: "D327",
    revieweeName: "Dương Thị Nhung",
    reviewerCode: "S306",
    reviewerName: "Nguyễn Thị Ngọc Anh",
    reviewType: 2,
  },
  {
    revieweeCode: "D169",
    revieweeName: "Trương Thu Hằng",
    reviewerCode: "D388",
    reviewerName: "Trần Phương Anh",
    reviewType: 2,
  },
  {
    revieweeCode: "D708",
    revieweeName: "Đinh Phương Thảo",
    reviewerCode: "D2680",
    reviewerName: "Nguyễn Thị Diệp",
    reviewType: 2,
  },
  {
    revieweeCode: "M30",
    revieweeName: "Lê Thị Mơ",
    reviewerCode: "D479",
    reviewerName: "Nguyễn Minh Ngọc",
    reviewType: 2,
  },
  {
    revieweeCode: "C037",
    revieweeName: "Nguyễn Thị Quỳnh",
    reviewerCode: "D3138",
    reviewerName: "Lê Thị Thanh Phương",
    reviewType: 2,
  },
  {
    revieweeCode: "M63",
    revieweeName: "Trịnh Thị Hạnh Linh",
    reviewerCode: "D5717",
    reviewerName: "Nguyễn Thị Mai Hương",
    reviewType: 2,
  },
  {
    revieweeCode: "D2680",
    revieweeName: "Nguyễn Thị Diệp",
    reviewerCode: "D5093",
    reviewerName: "Nguyễn Kim Hưng",
    reviewType: 2,
  },
  {
    revieweeCode: "E09",
    revieweeName: "Chu Huy Thắng",
    reviewerCode: "D388",
    reviewerName: "Trần Phương Anh",
    reviewType: 2,
  },
  {
    revieweeCode: "E62",
    revieweeName: "Nguyễn Xuân Trọng",
    reviewerCode: "D2825",
    reviewerName: "Phạm Ngọc Quỳnh - QC",
    reviewType: 2,
  },
  {
    revieweeCode: "E65",
    revieweeName: "Lê Quang Thành",
    reviewerCode: "D583",
    reviewerName: "Nguyễn Thế Anh",
    reviewType: 2,
  },
  {
    revieweeCode: "E80",
    revieweeName: "Nguyễn Mạnh Trường",
    reviewerCode: "D2607",
    reviewerName: "Nguyễn Bá Nam",
    reviewType: 2,
  },
  {
    revieweeCode: "D79",
    revieweeName: "Nguyễn Thị Mỹ Linh",
    reviewerCode: "D717",
    reviewerName: "Vũ Thúy Nhật",
    reviewType: 2,
  },
  {
    revieweeCode: "D2607",
    revieweeName: "Nguyễn Bá Nam",
    reviewerCode: "D169",
    reviewerName: "Trương Thu Hằng",
    reviewType: 2,
  },
  {
    revieweeCode: "M38",
    revieweeName: "Phạm Ngọc Quỳnh",
    reviewerCode: "D4424",
    reviewerName: "Nguyễn Đăng Thùy Dương",
    reviewType: 2,
  },
  {
    revieweeCode: "D2537",
    revieweeName: "Nguyễn Văn Thao",
    reviewerCode: "D352",
    reviewerName: "Hoàng Thị Dịu",
    reviewType: 2,
  },
  {
    revieweeCode: "E73",
    revieweeName: "Nguyễn Anh Tú",
    reviewerCode: "D557",
    reviewerName: "Vũ Thị Lành",
    reviewType: 2,
  },
  {
    revieweeCode: "D388",
    revieweeName: "Trần Phương Anh",
    reviewerCode: "D02",
    reviewerName: "Nguyễn Thu Thảo",
    reviewType: 2,
  },
  {
    revieweeCode: "D3982",
    revieweeName: "Hoàng Văn Luýt",
    reviewerCode: "D388",
    reviewerName: "Trần Phương Anh",
    reviewType: 2,
  },
  {
    revieweeCode: "D93",
    revieweeName: "Nguyễn Thúy Vi",
    reviewerCode: "D2607",
    reviewerName: "Nguyễn Bá Nam",
    reviewType: 2,
  },
  {
    revieweeCode: "S41",
    revieweeName: "Nguyễn Hữu Long",
    reviewerCode: "M38",
    reviewerName: "Phạm Ngọc Quỳnh - Ship",
    reviewType: 2,
  },
  {
    revieweeCode: "D5093",
    revieweeName: "Nguyễn Kim Hưng",
    reviewerCode: "M38",
    reviewerName: "Phạm Ngọc Quỳnh - Ship",
    reviewType: 2,
  },
  {
    revieweeCode: "D337",
    revieweeName: "Nguyễn Thành Nam",
    reviewerCode: "S306",
    reviewerName: "Nguyễn Thị Ngọc Anh",
    reviewType: 2,
  },
  {
    revieweeCode: "M70",
    revieweeName: "Phạm Khánh Linh",
    reviewerCode: "D708",
    reviewerName: "Đinh Phương Thảo",
    reviewType: 2,
  },
].map<IndividualForm>((d) => {
  return {
    ...d,
    slug: urlSlug.convert(
      `${d.revieweeCode} ${d.revieweeName} ${d.reviewType} ${d.reviewerCode}`
    ),
  };
});
