import { makeObservable, observable } from "mobx";
import { RootStore } from "./RootStore";
import * as urlSlug from "url-slug";

export interface Reviewee {
  revieweeCode: string;
  revieweeName: string;
  revieweeDepartment: string;
  revieweePositions: string[];
  // reviewLink: string;
  revieweeSlug: string;
  isManager: boolean;
}

export class RevieweeStore {
  rootStore: RootStore;

  reviewees = reviewees;

  constructor(rootStore: RootStore) {
    this.rootStore = rootStore;

    makeObservable(this, {
      reviewees: observable,
    });
  }
}

const reviewees = [
  {
    code: "M38",
    displayName: "Phạm Ngọc Quỳnh",
    position: "Saleadmin",
    email: "quynh.ngoc.pham.1997@gmail.com",
    isManager: 0,
    group: 1,
    pic: "Trần Anh Dũng",
    department: "E0",
    reviewerCode1: "M70",
    reviewerName1: "Phạm Khánh Linh",
    reviewerCode2: "D2680",
    reviewerName2: "Nguyễn Thị Diệp",
    reviewerCode3: "S41",
    reviewerName3: "Nguyễn Hữu Long",
    reviewerCode4: "D5093",
    reviewerName4: "Nguyễn Kim Hưng",
    reviewerCode5: "D5730",
    reviewerName5: "Nguyễn Tuấn Anh",
  },
  {
    code: "E73",
    displayName: "Nguyễn Anh Tú",
    position: "IT helpdesk",
    email: "anhtuas123@gmail.com",
    isManager: 1,
    group: 1,
    pic: "Trần Anh Dũng",
    department: "HC",
    reviewerCode1: "S146",
    reviewerName1: "Bùi Văn Vương",
    reviewerCode2: "D2537",
    reviewerName2: "Nguyễn Văn Thao",
    reviewerCode3: "E09",
    reviewerName3: "Chu Huy Thắng",
    reviewerCode4: "C037",
    reviewerName4: "Nguyễn Thị Quỳnh",
    reviewerCode5: "D93",
    reviewerName5: "Nguyễn Thúy Vi",
  },
  {
    code: "D5730",
    displayName: "Nguyễn Tuấn Anh",
    position: "Quản lý vận hành kho",
    email: "tuananhz4.pt@gmail.com",
    isManager: 1,
    group: 1,
    pic: "Trần Phương Anh",
    department: "Kho - ĐG",
    reviewerCode1: "D1516",
    reviewerName1: "Nguyễn Thùy Dương",
    reviewerCode2: "D557",
    reviewerName2: "Vũ Thị Lành",
    reviewerCode3: "M70",
    reviewerName3: "Phạm Khánh Linh",
    reviewerCode4: "M38",
    reviewerName4: "Phạm Ngọc Quỳnh",
    reviewerCode5: "S41",
    reviewerName5: "Nguyễn Hữu Long",
  },
  {
    code: "M70",
    displayName: "Phạm Khánh Linh",
    position: "Chuyên viên mua hàng",
    email: "klinhpham139@gmail.com",
    isManager: 1,
    group: 1,
    pic: "Vy Tuấn Anh",
    department: "Purchasing",
    reviewerCode1: "D6515",
    reviewerName1: "Toàn Thị Hà Giang",
    reviewerCode2: "D7288",
    reviewerName2: "Trần Thu Trang",
    reviewerCode3: "D2680",
    reviewerName3: "Nguyễn Thị Diệp",
    reviewerCode4: "D1516",
    reviewerName4: "Nguyễn Thùy Dương",
    reviewerCode5: "M38",
    reviewerName5: "Phạm Ngọc Quỳnh",
  },
  {
    code: "S110",
    displayName: "Nguyễn Văn Việt",
    position: "Graphic Designer",
    email: "vietxc2014@gmail.com",
    isManager: 0,
    group: 1,
    pic: "Vy Tuấn Anh",
    department: "OFFICE",
    reviewerCode1: "S146",
    reviewerName1: "Bùi Văn Vương",
    reviewerCode2: "E09",
    reviewerName2: "Chu Huy Thắng",
    reviewerCode3: "E062",
    reviewerName3: "Vũ Xuân Trọng",
    reviewerCode4: "D337",
    reviewerName4: "Nguyễn Thành Nam",
    reviewerCode5: "",
    reviewerName5: "",
  },
  {
    code: "M30",
    displayName: "Lê Thị Mơ",
    position: "Chuyên viên nhân sự tổng hợp",
    email: "lemoql1996@gmail.com",
    isManager: 1,
    group: 1,
    pic: "Lê Tuấn Hiệp",
    department: "HR",
    reviewerCode1: "D2607",
    reviewerName1: "Nguyễn Bá Nam",
    reviewerCode2: "M67",
    reviewerName2: "Phạm Thị Ngọc Thơ",
    reviewerCode3: "D1775",
    reviewerName3: "Triệu Hà Vy",
    reviewerCode4: "D7287",
    reviewerName4: "Doãn Thị Ngọc Ánh",
    reviewerCode5: "D6105",
    reviewerName5: "Ngô Quang Huấn",
  },
  {
    code: "D2607",
    displayName: "Nguyễn Bá Nam",
    position: "Chuyên viên nhân sự tổng hợp",
    email: "namnguyenba9x@gmail.com",
    isManager: 1,
    group: 1,
    pic: "Trần Anh Dũng",
    department: "HR",
    reviewerCode1: "S363",
    reviewerName1: "Vương Thị Hương Ly",
    reviewerCode2: "M30",
    reviewerName2: "Lê Thị Mơ",
    reviewerCode3: "D7287",
    reviewerName3: "Doãn Thị Ngọc Ánh",
    reviewerCode4: "D6105",
    reviewerName4: "Ngô Quang Huấn",
    reviewerCode5: "D79",
    reviewerName5: "Nguyễn Thị Mỹ Linh",
  },
  {
    code: "D583",
    displayName: "Nguyễn Thế Anh",
    position: "Quản lý sản xuất bếp",
    email: "theanh2726@gmail.com",
    isManager: 1,
    group: 1,
    pic: "Trần Phương Anh",
    department: "B1",
    reviewerCode1: "D479",
    reviewerName1: "Nguyễn Minh Ngọc",
    reviewerCode2: "S78",
    reviewerName2: "Bùi Thị Hương",
    reviewerCode3: "D169",
    reviewerName3: "Trương Thu Hằng",
    reviewerCode4: "E73",
    reviewerName4: "Nguyễn Anh Tú",
    reviewerCode5: "D703",
    reviewerName5: "Nguyễn Huyền Trang",
  },
  {
    code: "D337",
    displayName: "Nguyễn Thành Nam",
    position: "Kitchen Manager, Training Executive, TTL",
    email: "thanhnam06121997@gmail.com",
    isManager: 0,
    group: 1,
    pic: "Vy Tuấn Anh",
    department: "B2",
    reviewerCode1: "D1516",
    reviewerName1: "Nguyễn Thùy Dương",
    reviewerCode2: "D557",
    reviewerName2: "Vũ Thị Lành",
    reviewerCode3: "D93",
    reviewerName3: "Nguyễn Thúy Vi",
    reviewerCode4: "D583",
    reviewerName4: "Nguyễn Thế Anh",
    reviewerCode5: "",
    reviewerName5: "",
  },
  {
    code: "E65",
    displayName: "Lê Quang Thành",
    position: "Lập trình viên Full stack",
    email: "thanhquang2805@gmail.com",
    isManager: 0,
    group: 1,
    pic: "Lê Tuấn Hiệp",
    department: "Tech",
    reviewerCode1: "E73",
    reviewerName1: "Nguyễn Anh Tú",
    reviewerCode2: "S110",
    reviewerName2: "Nguyễn Văn Việt",
    reviewerCode3: "D6050",
    reviewerName3: "Nguyễn Đức Huy",
    reviewerCode4: "E09",
    reviewerName4: "Chu Huy Thắng",
    reviewerCode5: "D717",
    reviewerName5: "Vũ Thuý Nhật",
  },
  {
    code: "E80",
    displayName: "Nguyễn Mạnh Trường",
    position: "Lập trình viên Full stack",
    email: "truongmanh0912@gmail.com",
    isManager: 0,
    group: 1,
    pic: "Lê Tuấn Hiệp",
    department: "Tech",
    reviewerCode1: "D717",
    reviewerName1: "Vũ Thuý Nhật",
    reviewerCode2: "D708",
    reviewerName2: "Đinh Phương Thảo",
    reviewerCode3: "S110",
    reviewerName3: "Nguyễn Văn Việt",
    reviewerCode4: "S443",
    reviewerName4: "Lương Thuý Quỳnh",
    reviewerCode5: "E062",
    reviewerName5: "Vũ Xuân Trọng",
  },
  {
    code: "E62",
    displayName: "Vũ Xuân Trọng",
    position: "Lập trình viên Full stack",
    email: "xtrong49@gmail.com",
    isManager: 0,
    group: 1,
    pic: "Lê Tuấn Hiệp",
    department: "Tech",
    reviewerCode1: "D169",
    reviewerName1: "Trương Thu Hằng",
    reviewerCode2: "D717",
    reviewerName2: "Vũ Thúy Nhật",
    reviewerCode3: "D708",
    reviewerName3: "Đinh Phương Thảo",
    reviewerCode4: "S306",
    reviewerName4: "Nguyễn Thị Ngọc Anh",
    reviewerCode5: "M63",
    reviewerName5: "Trịnh Thị Hạnh Linh",
  },
  {
    code: "S363",
    displayName: "Vương Thị Hương Ly",
    position: "Chuyên viên nhân sự tổng hợp",
    email: "huonglyy312@gmail.com",
    isManager: 0,
    group: 1,
    pic: "Nguyễn Bá Nam",
    department: "HR2",
    reviewerCode1: "C037",
    reviewerName1: "Nguyễn Thị Quỳnh",
    reviewerCode2: "M30",
    reviewerName2: "Lê Thị Mơ",
    reviewerCode3: "D79",
    reviewerName3: "Nguyễn Thị Mỹ Linh",
    reviewerCode4: "M63",
    reviewerName4: "Trịnh Thị Hạnh Linh",
    reviewerCode5: "E09",
    reviewerName5: "Chu Huy Thắng",
  },
  {
    code: "D4163",
    displayName: "Lê Đăng Dũng",
    position: "Nhân viên giám sát chất lượng",
    email: "duongcongth@outlook.com.vn",
    isManager: 0,
    group: 1,
    pic: "Dương Thị Nhung",
    department: "QC",
    reviewerCode1: "E73",
    reviewerName1: "Nguyễn Anh Tú",
    reviewerCode2: "D93",
    reviewerName2: "Nguyễn Thúy Vi",
    reviewerCode3: "D1516",
    reviewerName3: "Nguyễn Thùy Dương",
    reviewerCode4: "D2825",
    reviewerName4: "Phạm Ngọc Quỳnh",
    reviewerCode5: "D337",
    reviewerName5: "Nguyễn Thành Nam",
  },
  {
    code: "D1516",
    displayName: "Nguyễn Thùy Dương",
    position: "Nhân viên giám sát chất lượng",
    email: "duongnguyenthuy276@gmail.com",
    isManager: 0,
    group: 1,
    pic: "Dương Thị Nhung",
    department: "QC",
    reviewerCode1: "D5730",
    reviewerName1: "Nguyễn Tuấn Anh",
    reviewerCode2: "M70",
    reviewerName2: "Phạm Khánh Linh",
    reviewerCode3: "D6515",
    reviewerName3: "Toàn Thị Hà Giang",
    reviewerCode4: "D5440",
    reviewerName4: "Nguyễn Tuấn Anh",
    reviewerCode5: "D2825",
    reviewerName5: "Phạm Ngọc Quỳnh",
  },
  {
    code: "D3982",
    displayName: "Hoàng Văn Luýt",
    position: "Nhân viên giám sát chất lượng",
    email: "hvl.luyt@gmail.com",
    isManager: 1,
    group: 1,
    pic: "Trần Anh Dũng",
    department: "QC",
    reviewerCode1: "D2607",
    reviewerName1: "Nguyễn Bá Nam",
    reviewerCode2: "S306",
    reviewerName2: "Nguyễn Thị Ngọc Anh",
    reviewerCode3: "D1886",
    reviewerName3: "Phùng Thị Ngọc Tuyết",
    reviewerCode4: "E73",
    reviewerName4: "Nguyễn Anh Tú",
    reviewerCode5: "D388",
    reviewerName5: "Trần Phương Anh",
  },
  {
    code: "D2825",
    displayName: "Phạm Ngọc Quỳnh",
    position: "Nhân viên giám sát chất lượng",
    email: "quynhngoc.1803@gmail.com",
    isManager: 0,
    group: 1,
    pic: "Dương Thị Nhung",
    department: "QC",
    reviewerCode1: "M63",
    reviewerName1: "Trịnh Thị Hạnh Linh",
    reviewerCode2: "D337",
    reviewerName2: "Nguyễn Thành Nam",
    reviewerCode3: "C037",
    reviewerName3: "Nguyễn Thị Quỳnh",
    reviewerCode4: "E73",
    reviewerName4: "Nguyễn Anh Tú",
    reviewerCode5: "D5730",
    reviewerName5: "Nguyễn Tuấn Anh",
  },
  {
    code: "D5440",
    displayName: "Nguyễn Tuấn Anh",
    position: "Nhân viên giám sát chất lượng",
    email: "tuananhnguyen020299@gmail.com",
    isManager: 0,
    group: 1,
    pic: "Dương Thị Nhung",
    department: "QC",
    reviewerCode1: "D2537",
    reviewerName1: "Nguyễn Văn Thao",
    reviewerCode2: "D1516",
    reviewerName2: "Nguyễn Thùy Dương",
    reviewerCode3: "E73",
    reviewerName3: "Nguyễn Anh Tú",
    reviewerCode4: "S306",
    reviewerName4: "Nguyễn Thị Ngọc Anh",
    reviewerCode5: "D2680",
    reviewerName5: "Nguyễn Thị Diệp",
  },
  {
    code: "D2537",
    displayName: "Nguyễn Văn Thao",
    position: "Nhân viên kỹ thuật điện nước",
    email: "ngocthao060690@gmail.com",
    isManager: 0,
    group: 1,
    pic: "Trần Anh Dũng",
    department: "HC",
    reviewerCode1: "E73",
    reviewerName1: "Nguyễn Anh Tú",
    reviewerCode2: "S146",
    reviewerName2: "Bùi Văn Vương",
    reviewerCode3: "D583",
    reviewerName3: "Nguyễn Thế Anh",
    reviewerCode4: "D2825",
    reviewerName4: "Phạm Ngọc Quỳnh",
    reviewerCode5: "D388",
    reviewerName5: "Trần Phương Anh",
  },
  {
    code: "S146",
    displayName: "Bùi Văn Vương",
    position: "Nhân viên kỹ thuật nội thất",
    email: "vuong7815@gmail.com",
    isManager: 0,
    group: 1,
    pic: "Trần Anh Dũng",
    department: "HC",
    reviewerCode1: "E73",
    reviewerName1: "Nguyễn Anh Tú",
    reviewerCode2: "D2537",
    reviewerName2: "Nguyễn Văn Thao",
    reviewerCode3: "D4163",
    reviewerName3: "Lê Đăng Dũng",
    reviewerCode4: "S110",
    reviewerName4: "Nguyễn Văn Việt",
    reviewerCode5: "D93",
    reviewerName5: "Nguyễn Thúy Vi",
  },
  {
    code: "M63",
    displayName: "Trịnh Thị Hạnh Linh",
    position: "Kế toán thuế",
    email: "thamtuongvang@gmail.com",
    isManager: 1,
    group: 1,
    pic: "Lê Tuấn Hiệp",
    department: "KT",
    reviewerCode1: "D5717",
    reviewerName1: "Nguyễn Thị Mai Hương",
    reviewerCode2: "M38",
    reviewerName2: "Phạm Ngọc Quỳnh",
    reviewerCode3: "S363",
    reviewerName3: "Vương Thị Hương Ly",
    reviewerCode4: "M70",
    reviewerName4: "Phạm Khánh Linh",
    reviewerCode5: "C037",
    reviewerName5: "Nguyễn Thị Quỳnh",
  },
  {
    code: "D2680",
    displayName: "Nguyễn Thị Diệp",
    position: "Nhân viên Logistic Full-time",
    email: "diepyeol61@gmail.com",
    isManager: 1,
    group: 1,
    pic: "Trần Anh Dũng",
    department: "Logistics",
    reviewerCode1: "M70",
    reviewerName1: "Phạm Khánh Linh",
    reviewerCode2: "D5093",
    reviewerName2: "Nguyễn Kim Hưng",
    reviewerCode3: "D3982",
    reviewerName3: "Hoàng Văn Luýt",
    reviewerCode4: "D4309",
    reviewerName4: "Nguyễn Văn Cương",
    reviewerCode5: "D5652",
    reviewerName5: "Phùng Thị Kim Chi",
  },
  {
    code: "D4309",
    displayName: "Nguyễn Văn Cương",
    position: "Chuyên viên phân tích dữ liệu",
    email: "cuongnv.1512@gmail.com",
    isManager: 0,
    group: 1,
    pic: "Lê Tuấn Hiệp",
    department: "BS",
    reviewerCode1: "D2680",
    reviewerName1: "Nguyễn Thị Diệp",
    reviewerCode2: "D169",
    reviewerName2: "Trương Thu Hằng",
    reviewerCode3: "M70",
    reviewerName3: "Phạm Khánh Linh",
    reviewerCode4: "D708",
    reviewerName4: "Đinh Phương Thảo",
    reviewerCode5: "D1516",
    reviewerName5: "Nguyễn Thùy Dương",
  },
  {
    code: "D708",
    displayName: "Đinh Phương Thảo",
    position: "Chuyên viên phân tích dữ liệu",
    email: "dinhphuongthaoqia@gmail.com",
    isManager: 0,
    group: 1,
    pic: "Lê Tuấn Hiệp",
    department: "BS",
    reviewerCode1: "M70",
    reviewerName1: "Phạm Khánh Linh",
    reviewerCode2: "D4309",
    reviewerName2: "Nguyễn Văn Cương",
    reviewerCode3: "E09",
    reviewerName3: "Chu Huy Thắng",
    reviewerCode4: "M38",
    reviewerName4: "Phạm Ngọc Quỳnh",
    reviewerCode5: "D169",
    reviewerName5: "Trương Thu Hằng",
  },
  {
    code: "D169",
    displayName: "Trương Thu Hằng",
    position: "Chuyên viên phân tích dữ liệu",
    email: "truongthuhang.28041998@gmail.com",
    isManager: 1,
    group: 1,
    pic: "Lê Tuấn Hiệp",
    department: "BS",
    reviewerCode1: "M38",
    reviewerName1: "Phạm Ngọc Quỳnh",
    reviewerCode2: "D6284",
    reviewerName2: "Nguyễn Thị Mai Hương",
    reviewerCode3: "D708",
    reviewerName3: "Đinh Phương Thảo",
    reviewerCode4: "E09",
    reviewerName4: "Chu Huy Thắng",
    reviewerCode5: "D4309",
    reviewerName5: "Nguyễn Văn Cương",
  },
  {
    code: "C037",
    displayName: "Nguyễn Thị Quỳnh",
    position: "Kế toán tổng hợp",
    email: "ntquynh05@gmail.com",
    isManager: 1,
    group: 1,
    pic: "Lê Tuấn Hiệp",
    department: "KT",
    reviewerCode1: "D5939",
    reviewerName1: "Nguyễn Đắc Dũng",
    reviewerCode2: "D3138",
    reviewerName2: "Lê Thị Thanh Phương",
    reviewerCode3: "M63",
    reviewerName3: "Trịnh Thị Hạnh Linh",
    reviewerCode4: "M70",
    reviewerName4: "Phạm Khánh Linh",
    reviewerCode5: "D169",
    reviewerName5: "Trương Thu Hằng",
  },
  {
    code: "E09",
    displayName: "Chu Huy Thắng",
    position: "Programming Lead",
    email: "chuthang205@gmail.com",
    isManager: 1,
    group: 1,
    pic: "Lê Tuấn Hiệp",
    department: "Tech",
    reviewerCode1: "D169",
    reviewerName1: "Trương Thu Hằng",
    reviewerCode2: "S306",
    reviewerName2: "Nguyễn Thị Ngọc Anh",
    reviewerCode3: "M38",
    reviewerName3: "Phạm Ngọc Quỳnh",
    reviewerCode4: "D2680",
    reviewerName4: "Nguyễn Thị Diệp",
    reviewerCode5: "S110",
    reviewerName5: "Nguyễn Văn Việt",
  },
  {
    code: "D327",
    displayName: "Dương Thị Nhung",
    position: "Quality Supervisor Manager",
    email: "duongnhung65@gmail.com",
    isManager: 1,
    group: 1,
    pic: "Vy Tuấn Anh",
    department: "QC",
    reviewerCode1: "D6795",
    reviewerName1: "Trần Thị Hiền",
    reviewerCode2: "D5440",
    reviewerName2: "Nguyễn Tuấn Anh",
    reviewerCode3: "D4163",
    reviewerName3: "Lê Đăng Dũng",
    reviewerCode4: "S306",
    reviewerName4: "Nguyễn Thị Ngọc Anh",
    reviewerCode5: "D703",
    reviewerName5: "Nguyễn Huyền Trang",
  },
  {
    code: "D557",
    displayName: "Vũ Thị Lành",
    position: "Quản lý đóng gói",
    email: "vulanhk59bka@gmail.com",
    isManager: 0,
    group: 1,
    pic: "Trần Phương Anh",
    department: "Kho - ĐG",
    reviewerCode1: "D337",
    reviewerName1: "Nguyễn Thành Nam",
    reviewerCode2: "S110",
    reviewerName2: "Nguyễn Văn Việt",
    reviewerCode3: "M70",
    reviewerName3: "Phạm Khánh Linh",
    reviewerCode4: "D6515",
    reviewerName4: "Toàn Thị Hà Giang",
    reviewerCode5: "S78",
    reviewerName5: "Bùi Thị Hương",
  },
  {
    code: "S78",
    displayName: "Bùi Thị Hương",
    position: "Quản lý vận hành kho",
    email: "buihuong17101997@gmail.com",
    isManager: 0,
    group: 1,
    pic: "Trần Phương Anh",
    department: "Kho - ĐG",
    reviewerCode1: "S306",
    reviewerName1: "Nguyễn Thị Ngọc Anh",
    reviewerCode2: "D5915",
    reviewerName2: "Phùng Hải Long",
    reviewerCode3: "D583",
    reviewerName3: "Nguyễn Thế Anh",
    reviewerCode4: "S41",
    reviewerName4: "Nguyễn Hữu Long",
    reviewerCode5: "M70",
    reviewerName5: "Phạm Khánh Linh",
  },
  {
    code: "D479",
    displayName: "Nguyễn Minh Ngọc",
    position: "Quản lý vận hành kho",
    email: "hastagminhngoc@gmail.com",
    isManager: 0,
    group: 1,
    pic: "Trần Phương Anh",
    department: "Kho - ĐG",
    reviewerCode1: "M30",
    reviewerName1: "Lê Thị Mơ",
    reviewerCode2: "S443",
    reviewerName2: "Lương Thúy Quỳnh",
    reviewerCode3: "D2607",
    reviewerName3: "Nguyễn Bá Nam",
    reviewerCode4: "D4309",
    reviewerName4: "Nguyễn Văn Cương",
    reviewerCode5: "D79",
    reviewerName5: "Nguyễn Thị Mỹ Linh",
  },
  {
    code: "D5093",
    displayName: "Nguyễn Kim Hưng",
    position: "Quản lý vận hành kho",
    email: "ngungsuong.nkh97@gmail.com",
    isManager: 1,
    group: 1,
    pic: "Trần Phương Anh",
    department: "Kho - ĐG",
    reviewerCode1: "D6515",
    reviewerName1: "Toàn Thị Hà Giang",
    reviewerCode2: "M38",
    reviewerName2: "Phạm Ngọc Quỳnh",
    reviewerCode3: "M70",
    reviewerName3: "Phạm Khánh Linh",
    reviewerCode4: "S78",
    reviewerName4: "Bùi Thị Hương",
    reviewerCode5: "D583",
    reviewerName5: "Nguyễn Thế Anh",
  },
  {
    code: "S41",
    displayName: "Nguyễn Hữu Long",
    position: "Quản lý vận hành kho",
    email: "nhlong2107@gmail.com",
    isManager: 1,
    group: 1,
    pic: "Trần Phương Anh",
    department: "Kho - ĐG",
    reviewerCode1: "D6515",
    reviewerName1: "Toàn Thị Hà Giang",
    reviewerCode2: "M38",
    reviewerName2: "Phạm Ngọc Quỳnh",
    reviewerCode3: "D2680",
    reviewerName3: "Nguyễn Thị Diệp",
    reviewerCode4: "D1516",
    reviewerName4: "Nguyễn Thùy Dương",
    reviewerCode5: "E73",
    reviewerName5: "Nguyễn Anh Tú",
  },
  {
    code: "D388",
    displayName: "Trần Phương Anh",
    position: "Quản lý vận hành kho",
    email: "tpa2498@gmail.com",
    isManager: 1,
    group: 1,
    pic: "Trần Anh Dũng",
    department: "Kho - ĐG",
    reviewerCode1: "D557",
    reviewerName1: "Vũ Thị Lành",
    reviewerCode2: "S78",
    reviewerName2: "Bùi Thị Hương",
    reviewerCode3: "D5093",
    reviewerName3: "Nguyễn Kim Hưng",
    reviewerCode4: "D169",
    reviewerName4: "Trương Thu Hằng",
    reviewerCode5: "M70",
    reviewerName5: "Phạm Khánh Linh",
  },
  {
    code: "D79",
    displayName: "Nguyễn Thị Mỹ Linh",
    position: "Chuyên viên đào tạo và phát triển",
    email: "linhxu271196@gmail.com",
    isManager: 1,
    group: 1,
    pic: "Lê Tuấn Hiệp",
    department: "Training",
    reviewerCode1: "D6050",
    reviewerName1: "Nguyễn Đức Huy",
    reviewerCode2: "D717",
    reviewerName2: "Vũ Thúy Nhật",
    reviewerCode3: "M30",
    reviewerName3: "Lê Thị Mơ",
    reviewerCode4: "D2607",
    reviewerName4: "Nguyễn Bá Nam",
    reviewerCode5: "D479",
    reviewerName5: "Nguyễn Minh Ngọc",
  },
  {
    code: "D93",
    displayName: "Nguyễn Thúy Vi",
    position: "Visual Merchandiser",
    email: "thuyvi11196@gmail.com",
    isManager: 0,
    group: 1,
    pic: "Trần Anh Dũng",
    department: "VM",
    reviewerCode1: "S146",
    reviewerName1: "Bùi Văn Vương",
    reviewerCode2: "E73",
    reviewerName2: "Nguyễn Anh Tú",
    reviewerCode3: "M70",
    reviewerName3: "Phạm Khánh Linh",
    reviewerCode4: "D2680",
    reviewerName4: "Nguyễn Thị Diệp",
    reviewerCode5: "D4163",
    reviewerName5: "Lê Đăng Dũng",
  },
  {
    code: "S306",
    displayName: "Nguyễn Thị Ngọc Anh",
    position: "Kiểm toán viên nội bộ",
    email: "ngocanhnguyen1698@gmail.com",
    isManager: 1,
    group: 1,
    pic: "Dương Thị Nhung",
    department: "Kiểm toán",
    reviewerCode1: "D5287",
    reviewerName1: "Nguyễn Thị Hoàng Cúc",
    reviewerCode2: "D5915",
    reviewerName2: "Phùng Hải Long",
    reviewerCode3: "D4553",
    reviewerName3: "Nguyễn Minh Hùng",
    reviewerCode4: "S78",
    reviewerName4: "Bùi Thị Hương",
    reviewerCode5: "D2607",
    reviewerName5: "Nguyễn Bá Nam",
  },
  {
    code: "D703",
    displayName: "Nguyễn Huyền Trang",
    position: "Chuyên viên nhân sự tổng hợp",
    email: "Blackpage60@gmail.com",
    isManager: 0,
    group: 1,
    pic: "Trần Phương Anh",
    department: "B1",
    reviewerCode1: "D479",
    reviewerName1: "Nguyễn Minh Ngọc",
    reviewerCode2: "D480",
    reviewerName2: "Phạm Văn Quí",
    reviewerCode3: "D1516",
    reviewerName3: "Nguyễn Thùy Dương",
    reviewerCode4: "D337",
    reviewerName4: "Nguyễn Thành Nam",
    reviewerCode5: "D583",
    reviewerName5: "Nguyễn Thế Anh",
  },
  {
    code: "D480",
    displayName: "Phạm Văn Quí",
    position: "Trưởng ca sản xuất",
    email: "quybeu1999@gmail.com",
    isManager: 0,
    group: 1,
    pic: "Trần Phương Anh",
    department: "B1",
    reviewerCode1: "D583",
    reviewerName1: "Nguyễn Thế Anh",
    reviewerCode2: "D703",
    reviewerName2: "Nguyễn Huyền Trang",
    reviewerCode3: "D1516",
    reviewerName3: "Nguyễn Thùy Dương",
    reviewerCode4: "E73",
    reviewerName4: "Nguyễn Anh Tú",
    reviewerCode5: "D456",
    reviewerName5: "Trần Thị Lệ Quyên",
  },
  {
    code: "D456",
    displayName: "Trần Thị Lệ Quyên",
    position: "Trưởng ca vận hành",
    email: "teddymcqueen99@gmail.com",
    isManager: 0,
    group: 1,
    pic: "Trần Phương Anh",
    department: "B1",
    reviewerCode1: "D703",
    reviewerName1: "Nguyễn Huyền Trang",
    reviewerCode2: "D583",
    reviewerName2: "Nguyễn Thế Anh",
    reviewerCode3: "D1516",
    reviewerName3: "Nguyễn Thùy Dương",
    reviewerCode4: "D480",
    reviewerName4: "Phạm Văn Quí",
    reviewerCode5: "",
    reviewerName5: "",
  },
  {
    code: "D7288",
    displayName: "Trần Thu Trang",
    position: "Chuyên viên mua hàng",
    email: "luongtrang04102015@gmail.com",
    isManager: 0,
    group: 2,
    pic: "Vy Tuấn Anh",
    department: "Purchasing",
    reviewerCode1: "",
    reviewerName1: "",
    reviewerCode2: "",
    reviewerName2: "",
    reviewerCode3: "",
    reviewerName3: "",
    reviewerCode4: "",
    reviewerName4: "",
    reviewerCode5: "",
    reviewerName5: "",
  },
  {
    code: "D6515",
    displayName: "Toàn Thị Hà Giang",
    position: "Chuyên viên mua hàng",
    email: "toanthihagiang123@gmail.com",
    isManager: 0,
    group: 2,
    pic: "Vy Tuấn Anh",
    department: "Purchasing",
    reviewerCode1: "",
    reviewerName1: "",
    reviewerCode2: "",
    reviewerName2: "",
    reviewerCode3: "",
    reviewerName3: "",
    reviewerCode4: "",
    reviewerName4: "",
    reviewerCode5: "",
    reviewerName5: "",
  },
  {
    code: "D6050",
    displayName: "Nguyễn Đức Huy",
    position: "Chuyên viên đào tạo và phát triển",
    email: "nguyenduchuy.neu@gmail.com",
    isManager: 0,
    group: 2,
    pic: "Lê Tuấn Hiệp",
    department: "Training",
    reviewerCode1: "",
    reviewerName1: "",
    reviewerCode2: "",
    reviewerName2: "",
    reviewerCode3: "",
    reviewerName3: "",
    reviewerCode4: "",
    reviewerName4: "",
    reviewerCode5: "",
    reviewerName5: "",
  },
  {
    code: "D717",
    displayName: "Vũ Thúy Nhật",
    position: "Chuyên viên đào tạo và phát triển",
    email: "v.thuy.nhatt@gmail.com",
    isManager: 0,
    group: 2,
    pic: "Lê Tuấn Hiệp",
    department: "Training",
    reviewerCode1: "",
    reviewerName1: "",
    reviewerCode2: "",
    reviewerName2: "",
    reviewerCode3: "",
    reviewerName3: "",
    reviewerCode4: "",
    reviewerName4: "",
    reviewerCode5: "",
    reviewerName5: "",
  },
  {
    code: "D6794",
    displayName: "Hoàng Đình Hiếu",
    position: "Nhân viên giám sát chất lượng",
    email: "hieuuuu2002@gmail.com",
    isManager: 0,
    group: 2,
    pic: "Dương Thị Nhung",
    department: "QC",
    reviewerCode1: "",
    reviewerName1: "",
    reviewerCode2: "",
    reviewerName2: "",
    reviewerCode3: "",
    reviewerName3: "",
    reviewerCode4: "",
    reviewerName4: "",
    reviewerCode5: "",
    reviewerName5: "",
  },
  {
    code: "D6795",
    displayName: "Trần Thị Hiền",
    position: "Nhân viên giám sát chất lượng",
    email: "tranhien1996.hn@gmail.com",
    isManager: 0,
    group: 2,
    pic: "Dương Thị Nhung",
    department: "QC",
    reviewerCode1: "",
    reviewerName1: "",
    reviewerCode2: "",
    reviewerName2: "",
    reviewerCode3: "",
    reviewerName3: "",
    reviewerCode4: "",
    reviewerName4: "",
    reviewerCode5: "",
    reviewerName5: "",
  },
  {
    code: "D5939",
    displayName: "Nguyễn Đắc Dũng",
    position: "Kế toán tổng hợp",
    email: "dungdark97@gmail.com",
    isManager: 0,
    group: 2,
    pic: "Lê Tuấn Hiệp",
    department: "KT",
    reviewerCode1: "",
    reviewerName1: "",
    reviewerCode2: "",
    reviewerName2: "",
    reviewerCode3: "",
    reviewerName3: "",
    reviewerCode4: "",
    reviewerName4: "",
    reviewerCode5: "",
    reviewerName5: "",
  },
  {
    code: "M67",
    displayName: "Phạm Thị Ngọc Thơ",
    position: "Nhân viên Truyền thông Tuyển dụng Full-time",
    email: "tho271299@gmail.com",
    isManager: 0,
    group: 2,
    pic: "Lê Thị Mơ",
    department: "HR1",
    reviewerCode1: "",
    reviewerName1: "",
    reviewerCode2: "",
    reviewerName2: "",
    reviewerCode3: "",
    reviewerName3: "",
    reviewerCode4: "",
    reviewerName4: "",
    reviewerCode5: "",
    reviewerName5: "",
  },
  {
    code: "D6105",
    displayName: "Ngô Quang Huấn",
    position: "Chuyên viên Tuyển dụng",
    email: "Quanghuanht1210@gmail.com",
    isManager: 1,
    group: 2,
    pic: "Nguyễn Bá Nam",
    department: "HR2",
    reviewerCode1: "",
    reviewerName1: "",
    reviewerCode2: "",
    reviewerName2: "",
    reviewerCode3: "",
    reviewerName3: "",
    reviewerCode4: "",
    reviewerName4: "",
    reviewerCode5: "",
    reviewerName5: "",
  },
  {
    code: "D7287",
    displayName: "Doãn Thị Ngọc Ánh",
    position: "Chuyên viên Tuyển dụng",
    email: "doanthingocanh1605@gmail.com",
    isManager: 1,
    group: 2,
    pic: "Nguyễn Bá Nam",
    department: "HR2",
    reviewerCode1: "",
    reviewerName1: "",
    reviewerCode2: "",
    reviewerName2: "",
    reviewerCode3: "",
    reviewerName3: "",
    reviewerCode4: "",
    reviewerName4: "",
    reviewerCode5: "",
    reviewerName5: "",
  },
].map<Reviewee>((d) => {
  return {
    revieweeCode: d.code,
    revieweeName: d.displayName,
    revieweeDepartment: d.department,
    revieweePositions: [d.position].filter((d) => !!d),
    revieweeSlug: urlSlug.convert(`${d.code} ${d.displayName}`),
    isManager: !!d.isManager,
  };
});
