import { makeObservable, observable } from "mobx";
import { RootStore } from "./RootStore";
import * as urlSlug from "url-slug";

export interface Reviewee {
  revieweeCode: string;
  revieweeName: string;
  revieweeDepartment: string;
  revieweePositions: string[];
  // reviewLink: string;
  revieweeSlug: string;
  isManager: boolean;
}

export class RevieweeStore {
  rootStore: RootStore;

  reviewees = reviewees;

  constructor(rootStore: RootStore) {
    this.rootStore = rootStore;

    makeObservable(this, {
      reviewees: observable,
    });
  }
}

const reviewees = [
  {
    revieweeCode: "D583",
    revieweeName: "Nguyễn Thế Anh",
    email: "theanh2726@gmail.com",
    "Số tháng làm việc": 27,
    supervisor: "Dương Thị Nhung",
    revieweeDepartment: "B1",
    revieweePosition1: "Quản lý sản xuất bếp",
    isManager: 1,
  },
  {
    revieweeCode: "S306",
    revieweeName: "Nguyễn Thị Ngọc Anh",
    email: "ngocanhnguyen1698@gmail.com",
    "Số tháng làm việc": 42,
    supervisor: "Dương Thị Nhung",
    revieweeDepartment: "Kiểm toán",
    revieweePosition1: "Kiểm toán viên nội bộ",
    isManager: 1,
  },
  {
    revieweeCode: "D1516",
    revieweeName: "Nguyễn Thùy Dương",
    email: "duongnguyenthuy276@gmail.com",
    "Số tháng làm việc": 20,
    supervisor: "Dương Thị Nhung",
    revieweeDepartment: "QC",
    revieweePosition1: "Nhân viên giám sát chất lượng",
    isManager: 1,
  },
  {
    revieweeCode: "D2825",
    revieweeName: "Phạm Ngọc Quỳnh",
    email: "quynhngoc.1803@gmail.com",
    "Số tháng làm việc": 13,
    supervisor: "Dương Thị Nhung",
    revieweeDepartment: "QC",
    revieweePosition1: "Nhân viên giám sát chất lượng",
    isManager: 0,
  },
  {
    revieweeCode: "D4163",
    revieweeName: "Lê Đăng Dũng",
    email: "duongcongth@outlook.com.vn",
    "Số tháng làm việc": 7,
    supervisor: "Dương Thị Nhung",
    revieweeDepartment: "QC",
    revieweePosition1: "Nhân viên giám sát chất lượng",
    isManager: 0,
  },
  {
    revieweeCode: "D5440",
    revieweeName: "Nguyễn Tuấn Anh",
    email: "tuananhnguyen020299@gmail.com",
    "Số tháng làm việc": 5,
    supervisor: "Dương Thị Nhung",
    revieweeDepartment: "QC",
    revieweePosition1: "Nhân viên giám sát chất lượng",
    isManager: 0,
  },
  {
    revieweeCode: "D327",
    revieweeName: "Dương Thị Nhung",
    email: "duongnhung65@gmail.com",
    "Số tháng làm việc": "",
    supervisor: "Vy Tuấn Anh",
    revieweeDepartment: "QC",
    revieweePosition1: "Nhân viên giám sát chất lượng",
    isManager: 1,
  },
  {
    revieweeCode: "D169",
    revieweeName: "Trương Thu Hằng",
    email: "truongthuhang.28041998@gmail.com",
    "Số tháng làm việc": 57,
    supervisor: "Lê Tuấn Hiệp",
    revieweeDepartment: "BS",
    revieweePosition1: "Business Analyst",
    isManager: 1,
  },
  {
    revieweeCode: "D708",
    revieweeName: "Đinh Phương Thảo",
    email: "dinhphuongthaoqia@gmail.com",
    "Số tháng làm việc": "",
    supervisor: "Lê Tuấn Hiệp",
    revieweeDepartment: "BS",
    revieweePosition1: "Business Analyst",
    isManager: 0,
  },
  {
    revieweeCode: "M30",
    revieweeName: "Lê Thị Mơ",
    email: "lemoql1996@gmail.com",
    "Số tháng làm việc": "",
    supervisor: "Lê Tuấn Hiệp",
    revieweeDepartment: "HR",
    revieweePosition1: "Chuyên viên nhân sự tổng hợp",
    isManager: 1,
  },
  {
    revieweeCode: "C037",
    revieweeName: "Nguyễn Thị Quỳnh",
    email: "ntquynh05@gmail.com",
    "Số tháng làm việc": 57,
    supervisor: "Lê Tuấn Hiệp",
    revieweeDepartment: "KT",
    revieweePosition1: "Kế toán tổng hợp",
    isManager: 1,
  },
  {
    revieweeCode: "M63",
    revieweeName: "Trịnh Thị Hạnh Linh",
    email: "thamtuongvang@gmail.com",
    "Số tháng làm việc": "",
    supervisor: "Lê Tuấn Hiệp",
    revieweeDepartment: "KT",
    revieweePosition1: "Kế toán thuế",
    isManager: 0,
  },
  {
    revieweeCode: "D2680",
    revieweeName: "Nguyễn Thị Diệp",
    email: "diepyeol61@gmail.com",
    "Số tháng làm việc": 13,
    supervisor: "Lê Tuấn Hiệp",
    revieweeDepartment: "Logistics",
    revieweePosition1: "Chuyên viên phân tích dữ liệu",
    isManager: 1,
  },
  {
    revieweeCode: "E09",
    revieweeName: "Chu Huy Thắng",
    email: "chuthang205@gmail.com",
    "Số tháng làm việc": 57,
    supervisor: "Lê Tuấn Hiệp",
    revieweeDepartment: "Tech",
    revieweePosition1: "Lập trình viên Full stack",
    isManager: 1,
  },
  {
    revieweeCode: "E62",
    revieweeName: "Nguyễn Xuân Trọng",
    email: "xtrong49@gmail.com",
    "Số tháng làm việc": 13,
    supervisor: "Lê Tuấn Hiệp",
    revieweeDepartment: "Tech",
    revieweePosition1: "Lập trình viên Full stack",
    isManager: 0,
  },
  {
    revieweeCode: "E65",
    revieweeName: "Lê Quang Thành",
    email: "thanhquang2805@gmail.com",
    "Số tháng làm việc": 11,
    supervisor: "Lê Tuấn Hiệp",
    revieweeDepartment: "Tech",
    revieweePosition1: "Lập trình viên Full stack",
    isManager: 0,
  },
  {
    revieweeCode: "E80",
    revieweeName: "Nguyễn Mạnh Trường",
    email: "truongmanh0912@gmail.com",
    "Số tháng làm việc": 6,
    supervisor: "Lê Tuấn Hiệp",
    revieweeDepartment: "Tech",
    revieweePosition1: "Lập trình viên Full stack",
    isManager: 0,
  },
  {
    revieweeCode: "D79",
    revieweeName: "Nguyễn Thị Mỹ Linh",
    email: "linhxu271196@gmail.com",
    "Số tháng làm việc": 67,
    supervisor: "Lê Tuấn Hiệp",
    revieweeDepartment: "Training",
    revieweePosition1: "Chuyên viên đào tạo và phát triển",
    isManager: 1,
  },
  {
    revieweeCode: "D2607",
    revieweeName: "Nguyễn Bá Nam",
    email: "namnguyenba9x@gmail.com",
    "Số tháng làm việc": 13,
    supervisor: "Trần Anh Dũng",
    revieweeDepartment: "Đánh giá",
    revieweePosition1: "Chuyên viên nhân sự tổng hợp",
    isManager: 1,
  },
  {
    revieweeCode: "M38",
    revieweeName: "Phạm Ngọc Quỳnh",
    email: "quynh.ngoc.pham.1997@gmail.com",
    "Số tháng làm việc": 43,
    supervisor: "Trần Anh Dũng",
    revieweeDepartment: "E0",
    revieweePosition1: "Chuyên viên bán hàng",
    isManager: 0,
  },
  {
    revieweeCode: "S146",
    revieweeName: "Bùi Văn Vương",
    email: "vuong7815@gmail.com",
    "Số tháng làm việc": 49,
    supervisor: "Trần Anh Dũng",
    revieweeDepartment: "HC",
    revieweePosition1: "Nhân viên kỹ thuật nội thất",
    isManager: 0,
  },
  {
    revieweeCode: "D2537",
    revieweeName: "Nguyễn Văn Thao",
    email: "ngocthao060690@gmail.com",
    "Số tháng làm việc": 14,
    supervisor: "Trần Anh Dũng",
    revieweeDepartment: "HC",
    revieweePosition1: "Nhân viên kỹ thuật điện nước",
    isManager: 0,
  },
  {
    revieweeCode: "E73",
    revieweeName: "Nguyễn Anh Tú",
    email: "anhtuas123@gmail.com",
    "Số tháng làm việc": 6,
    supervisor: "Trần Anh Dũng",
    revieweeDepartment: "HC",
    revieweePosition1: "IT helpdesk",
    isManager: 1,
  },
  {
    revieweeCode: "D388",
    revieweeName: "Trần Phương Anh",
    email: "tpa2498@gmail.com",
    "Số tháng làm việc": 38,
    supervisor: "Trần Anh Dũng",
    revieweeDepartment: "Kho - ĐG",
    revieweePosition1: "Trưởng phòng kho vận",
    isManager: 1,
  },
  {
    revieweeCode: "D3982",
    revieweeName: "Hoàng Văn Luýt",
    email: "hvl.luyt@gmail.com",
    "Số tháng làm việc": 8,
    supervisor: "Trần Anh Dũng",
    revieweeDepartment: "QC",
    revieweePosition1: "Nhân viên giám sát chất lượng",
    isManager: 1,
  },
  {
    revieweeCode: "D93",
    revieweeName: "Nguyễn Thúy Vi",
    email: "thuyvi11196@gmail.com",
    "Số tháng làm việc": 65,
    supervisor: "Trần Anh Dũng",
    revieweeDepartment: "VM",
    revieweePosition1: "Visual Merchandiser",
    isManager: 0,
  },
  {
    revieweeCode: "S41",
    revieweeName: "Nguyễn Hữu Long",
    email: "nhlong2107@gmail.com",
    "Số tháng làm việc": 59,
    supervisor: "Trần Phương Anh",
    revieweeDepartment: "Kho - ĐG",
    revieweePosition1: "Quản lý vận hành kho",
    isManager: 0,
  },
  {
    revieweeCode: "D557",
    revieweeName: "Vũ Thị Lành",
    email: "vulanhk59bka@gmail.com",
    "Số tháng làm việc": 32,
    supervisor: "Trần Phương Anh",
    revieweeDepartment: "Kho - ĐG",
    revieweePosition1: "Quản lý vận hành đóng gói",
    isManager: 0,
  },
  {
    revieweeCode: "D479",
    revieweeName: "Nguyễn Minh Ngọc",
    email: "hastagminhngoc@gmail.com",
    "Số tháng làm việc": 42,
    supervisor: "Trần Phương Anh",
    revieweeDepartment: "Kho - ĐG",
    revieweePosition1: "Chuyên viên nhân sự tổng hợp",
    isManager: 0,
  },
  {
    revieweeCode: "S78",
    revieweeName: "Bùi Thị Hương",
    email: "buihuong17101997@gmail.com",
    "Số tháng làm việc": 57,
    supervisor: "Trần Phương Anh",
    revieweeDepartment: "Kho - ĐG",
    revieweePosition1: "Kiểm toán viên nội bộ",
    isManager: 0,
  },
  {
    revieweeCode: "D5093",
    revieweeName: "Nguyễn Kim Hưng",
    email: "ngungsuong.nkh97@gmail.com",
    "Số tháng làm việc": 7,
    supervisor: "Trần Phương Anh",
    revieweeDepartment: "Kho - ĐG",
    revieweePosition1: "Quản lý vận hành kho",
    isManager: 0,
  },
  {
    revieweeCode: "D337",
    revieweeName: "Nguyễn Thành Nam",
    email: "thanhnam06121997@gmail.com",
    "Số tháng làm việc": 39,
    supervisor: "Vy Tuấn Anh",
    revieweeDepartment: "B2",
    revieweePosition1: "Chuyên viên nghiên cứu, phát triển sản phẩm",
    isManager: 0,
  },
  {
    revieweeCode: "S110",
    revieweeName: "Nguyễn Văn Việt",
    email: "vietxc2014@gmail.com",
    "Số tháng làm việc": 53,
    supervisor: "Vy Tuấn Anh",
    revieweeDepartment: "OFFICE",
    revieweePosition1: "Nhân viên thiết kế",
    isManager: 0,
  },
  {
    revieweeCode: "M70",
    revieweeName: "Phạm Khánh Linh",
    email: "klinhpham139@gmail.com",
    "Số tháng làm việc": 19,
    supervisor: "Vy Tuấn Anh",
    revieweeDepartment: "Purchasing",
    revieweePosition1: "Chuyên viên mua hàng",
    isManager: 1,
  },
].map<Reviewee>((d) => {
  return {
    revieweeCode: d.revieweeCode,
    revieweeName: d.revieweeName,
    revieweeDepartment: d.revieweeDepartment,
    revieweePositions: [d.revieweePosition1].filter((d) => !!d),
    revieweeSlug: urlSlug.convert(`${d.revieweeCode} ${d.revieweeName}`),
    isManager: !!d.isManager,
  };
});
